///|
test "bmc-galileo-8.cnf" {
  check_sat("./dimacs/bmc/bmc-galileo-8.cnf", print_metrics=true)
}

///|
test "bmc-ibm-1.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-1.cnf", print_metrics=true)
}

///|
test "bmc-ibm-2.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-2.cnf", print_metrics=true)
}

///|
test "bmc-ibm-10.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-10.cnf", print_metrics=true)
}

///|
test "bmc-ibm-13.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-13.cnf", print_metrics=true)
}

///|
test "bmc-ibm-5.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-5.cnf", print_metrics=true)
}

///|
test "bmc-ibm-7.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-7.cnf", print_metrics=true)
}

///|
test "bmc-ibm-12.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-12.cnf", print_metrics=true)
}

///|
test "bmc-ibm-4.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-4.cnf", print_metrics=true)
}

///|
test "bmc-ibm-11.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-11.cnf", print_metrics=true)
}

///|
test "bmc-galileo-9.cnf" {
  check_sat("./dimacs/bmc/bmc-galileo-9.cnf", print_metrics=true)
}

///|
test "bmc-ibm-3.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-3.cnf", print_metrics=true)
}

///|
test "bmc-ibm-6.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-6.cnf", print_metrics=true)
}
