///|
test "bmc-galileo-8.cnf" {
  check_sat("./dimacs/bmc/bmc-galileo-8.cnf")
}

///|
test "bmc-ibm-1.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-1.cnf")
}

///|
test "bmc-ibm-2.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-2.cnf")
}

///|
test "bmc-ibm-10.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-10.cnf")
}

///|
test "bmc-ibm-13.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-13.cnf")
}

///|
test "bmc-ibm-5.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-5.cnf")
}

///|
test "bmc-ibm-7.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-7.cnf")
}

///|
test "bmc-ibm-12.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-12.cnf")
}

///|
test "bmc-ibm-4.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-4.cnf")
}

///|
test "bmc-ibm-11.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-11.cnf")
}

///|
test "bmc-galileo-9.cnf" {
  check_sat("./dimacs/bmc/bmc-galileo-9.cnf")
}

///|
test "bmc-ibm-3.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-3.cnf")
}

///|
test "bmc-ibm-6.cnf" {
  check_sat("./dimacs/bmc/bmc-ibm-6.cnf")
}
