///|
test "flat200-8.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-8.cnf")
}

///|
test "flat200-3.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-3.cnf")
}

///|
test "flat200-72.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-72.cnf")
}

///|
test "flat200-40.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-40.cnf")
}

///|
test "flat200-18.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-18.cnf")
}

///|
test "flat200-68.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-68.cnf")
}

///|
test "flat200-92.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-92.cnf")
}

///|
test "flat200-93.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-93.cnf")
}

///|
test "flat200-38.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-38.cnf")
}

///|
test "flat200-48.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-48.cnf")
}

///|
test "flat200-2.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-2.cnf")
}

///|
test "flat200-95.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-95.cnf")
}

///|
test "flat200-6.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-6.cnf")
}

///|
test "flat200-35.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-35.cnf")
}

///|
test "flat200-76.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-76.cnf")
}

///|
test "flat200-65.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-65.cnf")
}

///|
test "flat200-50.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-50.cnf")
}

///|
test "flat200-90.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-90.cnf")
}

///|
test "flat200-32.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-32.cnf")
}

///|
test "flat200-29.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-29.cnf")
}

///|
test "flat200-56.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-56.cnf")
}

///|
test "flat200-64.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-64.cnf")
}

///|
test "flat200-43.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-43.cnf")
}

///|
test "flat200-44.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-44.cnf")
}

///|
test "flat200-11.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-11.cnf")
}

///|
test "flat200-36.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-36.cnf")
}

///|
test "flat200-41.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-41.cnf")
}

///|
test "flat200-81.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-81.cnf")
}

///|
test "flat200-5.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-5.cnf")
}

///|
test "flat200-73.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-73.cnf")
}

///|
test "flat200-7.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-7.cnf")
}

///|
test "flat200-51.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-51.cnf")
}

///|
test "flat200-77.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-77.cnf")
}

///|
test "flat200-94.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-94.cnf")
}

///|
test "flat200-91.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-91.cnf")
}

///|
test "flat200-98.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-98.cnf")
}

///|
test "flat200-52.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-52.cnf")
}

///|
test "flat200-16.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-16.cnf")
}

///|
test "flat200-37.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-37.cnf")
}

///|
test "flat200-1.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-1.cnf")
}

///|
test "flat200-55.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-55.cnf")
}

///|
test "flat200-99.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-99.cnf")
}

///|
test "flat200-87.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-87.cnf")
}

///|
test "flat200-53.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-53.cnf")
}

///|
test "flat200-28.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-28.cnf")
}

///|
test "flat200-17.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-17.cnf")
}

///|
test "flat200-47.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-47.cnf")
}

///|
test "flat200-100.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-100.cnf")
}

///|
test "flat200-69.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-69.cnf")
}

///|
test "flat200-19.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-19.cnf")
}

///|
test "flat200-78.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-78.cnf")
}

///|
test "flat200-61.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-61.cnf")
}

///|
test "flat200-58.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-58.cnf")
}

///|
test "flat200-54.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-54.cnf")
}

///|
test "flat200-85.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-85.cnf")
}

///|
test "flat200-84.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-84.cnf")
}

///|
test "flat200-24.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-24.cnf")
}

///|
test "flat200-13.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-13.cnf")
}

///|
test "flat200-31.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-31.cnf")
}

///|
test "flat200-83.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-83.cnf")
}

///|
test "flat200-15.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-15.cnf")
}

///|
test "flat200-66.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-66.cnf")
}

///|
test "flat200-20.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-20.cnf")
}

///|
test "flat200-89.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-89.cnf")
}

///|
test "flat200-71.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-71.cnf")
}

///|
test "flat200-30.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-30.cnf")
}

///|
test "flat200-80.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-80.cnf")
}

///|
test "flat200-97.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-97.cnf")
}

///|
test "flat200-74.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-74.cnf")
}

///|
test "flat200-63.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-63.cnf")
}

///|
test "flat200-49.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-49.cnf")
}

///|
test "flat200-34.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-34.cnf")
}

///|
test "flat200-60.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-60.cnf")
}

///|
test "flat200-23.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-23.cnf")
}

///|
test "flat200-4.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-4.cnf")
}

///|
test "flat200-27.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-27.cnf")
}

///|
test "flat200-42.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-42.cnf")
}

///|
test "flat200-70.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-70.cnf")
}

///|
test "flat200-22.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-22.cnf")
}

///|
test "flat200-62.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-62.cnf")
}

///|
test "flat200-82.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-82.cnf")
}

///|
test "flat200-14.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-14.cnf")
}

///|
test "flat200-79.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-79.cnf")
}

///|
test "flat200-9.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-9.cnf")
}

///|
test "flat200-39.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-39.cnf")
}

///|
test "flat200-67.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-67.cnf")
}

///|
test "flat200-46.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-46.cnf")
}

///|
test "flat200-88.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-88.cnf")
}

///|
test "flat200-96.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-96.cnf")
}

///|
test "flat200-86.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-86.cnf")
}

///|
test "flat200-45.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-45.cnf")
}

///|
test "flat200-75.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-75.cnf")
}

///|
test "flat200-12.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-12.cnf")
}

///|
test "flat200-33.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-33.cnf")
}

///|
test "flat200-10.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-10.cnf")
}

///|
test "flat200-59.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-59.cnf")
}

///|
test "flat200-26.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-26.cnf")
}

///|
test "flat200-57.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-57.cnf")
}

///|
test "flat200-21.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-21.cnf")
}

///|
test "flat200-25.cnf" {
  check_sat("./dimacs/flat200v479e/flat200-25.cnf")
}
