///|
test "flat100-69.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-69.cnf")
}

///|
test "flat100-79.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-79.cnf")
}

///|
test "flat100-82.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-82.cnf")
}

///|
test "flat100-48.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-48.cnf")
}

///|
test "flat100-35.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-35.cnf")
}

///|
test "flat100-38.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-38.cnf")
}

///|
test "flat100-73.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-73.cnf")
}

///|
test "flat100-32.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-32.cnf")
}

///|
test "flat100-67.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-67.cnf")
}

///|
test "flat100-27.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-27.cnf")
}

///|
test "flat100-43.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-43.cnf")
}

///|
test "flat100-45.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-45.cnf")
}

///|
test "flat100-46.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-46.cnf")
}

///|
test "flat100-24.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-24.cnf")
}

///|
test "flat100-28.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-28.cnf")
}

///|
test "flat100-55.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-55.cnf")
}

///|
test "flat100-100.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-100.cnf")
}

///|
test "flat100-76.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-76.cnf")
}

///|
test "flat100-25.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-25.cnf")
}

///|
test "flat100-90.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-90.cnf")
}

///|
test "flat100-33.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-33.cnf")
}

///|
test "flat100-14.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-14.cnf")
}

///|
test "flat100-26.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-26.cnf")
}

///|
test "flat100-47.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-47.cnf")
}

///|
test "flat100-91.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-91.cnf")
}

///|
test "flat100-58.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-58.cnf")
}

///|
test "flat100-96.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-96.cnf")
}

///|
test "flat100-31.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-31.cnf")
}

///|
test "flat100-88.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-88.cnf")
}

///|
test "flat100-12.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-12.cnf")
}

///|
test "flat100-84.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-84.cnf")
}

///|
test "flat100-16.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-16.cnf")
}

///|
test "flat100-30.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-30.cnf")
}

///|
test "flat100-94.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-94.cnf")
}

///|
test "flat100-80.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-80.cnf")
}

///|
test "flat100-62.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-62.cnf")
}

///|
test "flat100-2.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-2.cnf")
}

///|
test "flat100-64.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-64.cnf")
}

///|
test "flat100-21.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-21.cnf")
}

///|
test "flat100-13.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-13.cnf")
}

///|
test "flat100-66.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-66.cnf")
}

///|
test "flat100-49.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-49.cnf")
}

///|
test "flat100-19.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-19.cnf")
}

///|
test "flat100-60.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-60.cnf")
}

///|
test "flat100-6.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-6.cnf")
}

///|
test "flat100-81.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-81.cnf")
}

///|
test "flat100-74.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-74.cnf")
}

///|
test "flat100-44.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-44.cnf")
}

///|
test "flat100-37.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-37.cnf")
}

///|
test "flat100-70.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-70.cnf")
}

///|
test "flat100-77.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-77.cnf")
}

///|
test "flat100-9.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-9.cnf")
}

///|
test "flat100-3.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-3.cnf")
}

///|
test "flat100-23.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-23.cnf")
}

///|
test "flat100-65.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-65.cnf")
}

///|
test "flat100-57.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-57.cnf")
}

///|
test "flat100-22.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-22.cnf")
}

///|
test "flat100-86.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-86.cnf")
}

///|
test "flat100-11.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-11.cnf")
}

///|
test "flat100-18.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-18.cnf")
}

///|
test "flat100-97.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-97.cnf")
}

///|
test "flat100-98.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-98.cnf")
}

///|
test "flat100-40.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-40.cnf")
}

///|
test "flat100-53.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-53.cnf")
}

///|
test "flat100-52.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-52.cnf")
}

///|
test "flat100-68.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-68.cnf")
}

///|
test "flat100-15.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-15.cnf")
}

///|
test "flat100-83.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-83.cnf")
}

///|
test "flat100-8.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-8.cnf")
}

///|
test "flat100-36.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-36.cnf")
}

///|
test "flat100-7.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-7.cnf")
}

///|
test "flat100-93.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-93.cnf")
}

///|
test "flat100-5.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-5.cnf")
}

///|
test "flat100-61.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-61.cnf")
}

///|
test "flat100-71.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-71.cnf")
}

///|
test "flat100-92.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-92.cnf")
}

///|
test "flat100-87.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-87.cnf")
}

///|
test "flat100-10.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-10.cnf")
}

///|
test "flat100-34.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-34.cnf")
}

///|
test "flat100-99.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-99.cnf")
}

///|
test "flat100-17.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-17.cnf")
}

///|
test "flat100-75.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-75.cnf")
}

///|
test "flat100-50.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-50.cnf")
}

///|
test "flat100-78.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-78.cnf")
}

///|
test "flat100-39.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-39.cnf")
}

///|
test "flat100-20.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-20.cnf")
}

///|
test "flat100-4.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-4.cnf")
}

///|
test "flat100-59.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-59.cnf")
}

///|
test "flat100-1.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-1.cnf")
}

///|
test "flat100-41.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-41.cnf")
}

///|
test "flat100-95.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-95.cnf")
}

///|
test "flat100-85.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-85.cnf")
}

///|
test "flat100-54.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-54.cnf")
}

///|
test "flat100-42.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-42.cnf")
}

///|
test "flat100-63.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-63.cnf")
}

///|
test "flat100-29.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-29.cnf")
}

///|
test "flat100-72.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-72.cnf")
}

///|
test "flat100-56.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-56.cnf")
}

///|
test "flat100-51.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-51.cnf")
}

///|
test "flat100-89.cnf" {
  check_sat("./dimacs/flat100v239e/flat100-89.cnf")
}
