///|
test "flat50-586.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-586.cnf")
}

///|
test "flat50-226.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-226.cnf")
}

///|
test "flat50-490.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-490.cnf")
}

///|
test "flat50-503.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-503.cnf")
}

///|
test "flat50-927.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-927.cnf")
}

///|
test "flat50-700.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-700.cnf")
}

///|
test "flat50-388.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-388.cnf")
}

///|
test "flat50-46.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-46.cnf")
}

///|
test "flat50-710.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-710.cnf")
}

///|
test "flat50-896.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-896.cnf")
}

///|
test "flat50-868.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-868.cnf")
}

///|
test "flat50-154.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-154.cnf")
}

///|
test "flat50-561.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-561.cnf")
}

///|
test "flat50-696.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-696.cnf")
}

///|
test "flat50-341.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-341.cnf")
}

///|
test "flat50-526.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-526.cnf")
}

///|
test "flat50-557.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-557.cnf")
}

///|
test "flat50-572.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-572.cnf")
}

///|
test "flat50-918.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-918.cnf")
}

///|
test "flat50-672.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-672.cnf")
}

///|
test "flat50-856.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-856.cnf")
}

///|
test "flat50-358.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-358.cnf")
}

///|
test "flat50-460.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-460.cnf")
}

///|
test "flat50-758.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-758.cnf")
}

///|
test "flat50-820.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-820.cnf")
}

///|
test "flat50-860.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-860.cnf")
}

///|
test "flat50-583.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-583.cnf")
}

///|
test "flat50-364.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-364.cnf")
}

///|
test "flat50-813.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-813.cnf")
}

///|
test "flat50-906.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-906.cnf")
}

///|
test "flat50-864.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-864.cnf")
}

///|
test "flat50-778.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-778.cnf")
}

///|
test "flat50-110.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-110.cnf")
}

///|
test "flat50-949.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-949.cnf")
}

///|
test "flat50-264.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-264.cnf")
}

///|
test "flat50-975.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-975.cnf")
}

///|
test "flat50-100.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-100.cnf")
}

///|
test "flat50-736.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-736.cnf")
}

///|
test "flat50-347.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-347.cnf")
}

///|
test "flat50-699.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-699.cnf")
}

///|
test "flat50-564.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-564.cnf")
}

///|
test "flat50-963.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-963.cnf")
}

///|
test "flat50-617.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-617.cnf")
}

///|
test "flat50-851.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-851.cnf")
}

///|
test "flat50-761.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-761.cnf")
}

///|
test "flat50-359.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-359.cnf")
}

///|
test "flat50-469.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-469.cnf")
}

///|
test "flat50-657.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-657.cnf")
}

///|
test "flat50-451.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-451.cnf")
}

///|
test "flat50-452.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-452.cnf")
}

///|
test "flat50-584.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-584.cnf")
}

///|
test "flat50-404.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-404.cnf")
}

///|
test "flat50-481.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-481.cnf")
}

///|
test "flat50-57.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-57.cnf")
}

///|
test "flat50-306.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-306.cnf")
}

///|
test "flat50-691.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-691.cnf")
}

///|
test "flat50-633.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-633.cnf")
}

///|
test "flat50-793.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-793.cnf")
}

///|
test "flat50-204.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-204.cnf")
}

///|
test "flat50-948.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-948.cnf")
}

///|
test "flat50-7.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-7.cnf")
}

///|
test "flat50-614.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-614.cnf")
}

///|
test "flat50-753.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-753.cnf")
}

///|
test "flat50-134.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-134.cnf")
}

///|
test "flat50-370.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-370.cnf")
}

///|
test "flat50-282.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-282.cnf")
}

///|
test "flat50-620.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-620.cnf")
}

///|
test "flat50-537.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-537.cnf")
}

///|
test "flat50-638.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-638.cnf")
}

///|
test "flat50-229.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-229.cnf")
}

///|
test "flat50-131.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-131.cnf")
}

///|
test "flat50-165.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-165.cnf")
}

///|
test "flat50-414.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-414.cnf")
}

///|
test "flat50-765.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-765.cnf")
}

///|
test "flat50-303.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-303.cnf")
}

///|
test "flat50-539.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-539.cnf")
}

///|
test "flat50-859.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-859.cnf")
}

///|
test "flat50-3.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-3.cnf")
}

///|
test "flat50-384.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-384.cnf")
}

///|
test "flat50-692.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-692.cnf")
}

///|
test "flat50-428.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-428.cnf")
}

///|
test "flat50-814.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-814.cnf")
}

///|
test "flat50-168.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-168.cnf")
}

///|
test "flat50-1000.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-1000.cnf")
}

///|
test "flat50-243.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-243.cnf")
}

///|
test "flat50-998.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-998.cnf")
}

///|
test "flat50-76.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-76.cnf")
}

///|
test "flat50-274.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-274.cnf")
}

///|
test "flat50-502.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-502.cnf")
}

///|
test "flat50-713.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-713.cnf")
}

///|
test "flat50-170.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-170.cnf")
}

///|
test "flat50-762.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-762.cnf")
}

///|
test "flat50-688.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-688.cnf")
}

///|
test "flat50-538.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-538.cnf")
}

///|
test "flat50-71.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-71.cnf")
}

///|
test "flat50-419.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-419.cnf")
}

///|
test "flat50-899.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-899.cnf")
}

///|
test "flat50-90.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-90.cnf")
}

///|
test "flat50-580.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-580.cnf")
}

///|
test "flat50-630.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-630.cnf")
}

///|
test "flat50-867.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-867.cnf")
}

///|
test "flat50-318.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-318.cnf")
}

///|
test "flat50-260.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-260.cnf")
}

///|
test "flat50-495.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-495.cnf")
}

///|
test "flat50-528.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-528.cnf")
}

///|
test "flat50-659.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-659.cnf")
}

///|
test "flat50-397.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-397.cnf")
}

///|
test "flat50-680.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-680.cnf")
}

///|
test "flat50-842.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-842.cnf")
}

///|
test "flat50-449.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-449.cnf")
}

///|
test "flat50-136.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-136.cnf")
}

///|
test "flat50-64.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-64.cnf")
}

///|
test "flat50-579.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-579.cnf")
}

///|
test "flat50-745.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-745.cnf")
}

///|
test "flat50-280.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-280.cnf")
}

///|
test "flat50-589.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-589.cnf")
}

///|
test "flat50-748.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-748.cnf")
}

///|
test "flat50-889.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-889.cnf")
}

///|
test "flat50-291.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-291.cnf")
}

///|
test "flat50-746.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-746.cnf")
}

///|
test "flat50-627.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-627.cnf")
}

///|
test "flat50-898.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-898.cnf")
}

///|
test "flat50-884.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-884.cnf")
}

///|
test "flat50-382.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-382.cnf")
}

///|
test "flat50-951.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-951.cnf")
}

///|
test "flat50-181.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-181.cnf")
}

///|
test "flat50-392.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-392.cnf")
}

///|
test "flat50-648.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-648.cnf")
}

///|
test "flat50-879.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-879.cnf")
}

///|
test "flat50-417.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-417.cnf")
}

///|
test "flat50-981.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-981.cnf")
}

///|
test "flat50-216.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-216.cnf")
}

///|
test "flat50-903.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-903.cnf")
}

///|
test "flat50-315.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-315.cnf")
}

///|
test "flat50-190.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-190.cnf")
}

///|
test "flat50-712.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-712.cnf")
}

///|
test "flat50-977.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-977.cnf")
}

///|
test "flat50-566.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-566.cnf")
}

///|
test "flat50-339.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-339.cnf")
}

///|
test "flat50-507.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-507.cnf")
}

///|
test "flat50-293.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-293.cnf")
}

///|
test "flat50-577.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-577.cnf")
}

///|
test "flat50-777.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-777.cnf")
}

///|
test "flat50-135.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-135.cnf")
}

///|
test "flat50-811.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-811.cnf")
}

///|
test "flat50-480.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-480.cnf")
}

///|
test "flat50-773.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-773.cnf")
}

///|
test "flat50-735.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-735.cnf")
}

///|
test "flat50-875.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-875.cnf")
}

///|
test "flat50-810.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-810.cnf")
}

///|
test "flat50-252.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-252.cnf")
}

///|
test "flat50-420.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-420.cnf")
}

///|
test "flat50-344.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-344.cnf")
}

///|
test "flat50-387.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-387.cnf")
}

///|
test "flat50-28.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-28.cnf")
}

///|
test "flat50-74.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-74.cnf")
}

///|
test "flat50-669.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-669.cnf")
}

///|
test "flat50-974.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-974.cnf")
}

///|
test "flat50-52.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-52.cnf")
}

///|
test "flat50-616.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-616.cnf")
}

///|
test "flat50-149.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-149.cnf")
}

///|
test "flat50-30.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-30.cnf")
}

///|
test "flat50-547.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-547.cnf")
}

///|
test "flat50-450.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-450.cnf")
}

///|
test "flat50-756.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-756.cnf")
}

///|
test "flat50-936.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-936.cnf")
}

///|
test "flat50-647.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-647.cnf")
}

///|
test "flat50-24.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-24.cnf")
}

///|
test "flat50-720.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-720.cnf")
}

///|
test "flat50-95.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-95.cnf")
}

///|
test "flat50-575.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-575.cnf")
}

///|
test "flat50-831.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-831.cnf")
}

///|
test "flat50-310.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-310.cnf")
}

///|
test "flat50-803.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-803.cnf")
}

///|
test "flat50-151.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-151.cnf")
}

///|
test "flat50-847.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-847.cnf")
}

///|
test "flat50-554.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-554.cnf")
}

///|
test "flat50-352.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-352.cnf")
}

///|
test "flat50-228.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-228.cnf")
}

///|
test "flat50-337.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-337.cnf")
}

///|
test "flat50-915.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-915.cnf")
}

///|
test "flat50-947.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-947.cnf")
}

///|
test "flat50-68.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-68.cnf")
}

///|
test "flat50-109.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-109.cnf")
}

///|
test "flat50-747.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-747.cnf")
}

///|
test "flat50-679.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-679.cnf")
}

///|
test "flat50-160.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-160.cnf")
}

///|
test "flat50-578.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-578.cnf")
}

///|
test "flat50-822.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-822.cnf")
}

///|
test "flat50-923.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-923.cnf")
}

///|
test "flat50-805.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-805.cnf")
}

///|
test "flat50-133.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-133.cnf")
}

///|
test "flat50-499.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-499.cnf")
}

///|
test "flat50-97.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-97.cnf")
}

///|
test "flat50-464.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-464.cnf")
}

///|
test "flat50-348.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-348.cnf")
}

///|
test "flat50-548.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-548.cnf")
}

///|
test "flat50-326.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-326.cnf")
}

///|
test "flat50-208.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-208.cnf")
}

///|
test "flat50-980.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-980.cnf")
}

///|
test "flat50-596.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-596.cnf")
}

///|
test "flat50-919.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-919.cnf")
}

///|
test "flat50-970.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-970.cnf")
}

///|
test "flat50-478.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-478.cnf")
}

///|
test "flat50-592.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-592.cnf")
}

///|
test "flat50-456.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-456.cnf")
}

///|
test "flat50-231.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-231.cnf")
}

///|
test "flat50-640.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-640.cnf")
}

///|
test "flat50-997.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-997.cnf")
}

///|
test "flat50-797.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-797.cnf")
}

///|
test "flat50-44.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-44.cnf")
}

///|
test "flat50-514.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-514.cnf")
}

///|
test "flat50-398.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-398.cnf")
}

///|
test "flat50-440.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-440.cnf")
}

///|
test "flat50-288.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-288.cnf")
}

///|
test "flat50-475.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-475.cnf")
}

///|
test "flat50-513.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-513.cnf")
}

///|
test "flat50-830.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-830.cnf")
}

///|
test "flat50-996.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-996.cnf")
}

///|
test "flat50-625.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-625.cnf")
}

///|
test "flat50-937.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-937.cnf")
}

///|
test "flat50-29.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-29.cnf")
}

///|
test "flat50-759.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-759.cnf")
}

///|
test "flat50-520.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-520.cnf")
}

///|
test "flat50-281.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-281.cnf")
}

///|
test "flat50-508.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-508.cnf")
}

///|
test "flat50-321.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-321.cnf")
}

///|
test "flat50-53.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-53.cnf")
}

///|
test "flat50-789.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-789.cnf")
}

///|
test "flat50-36.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-36.cnf")
}

///|
test "flat50-728.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-728.cnf")
}

///|
test "flat50-663.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-663.cnf")
}

///|
test "flat50-220.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-220.cnf")
}

///|
test "flat50-236.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-236.cnf")
}

///|
test "flat50-600.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-600.cnf")
}

///|
test "flat50-819.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-819.cnf")
}

///|
test "flat50-966.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-966.cnf")
}

///|
test "flat50-711.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-711.cnf")
}

///|
test "flat50-752.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-752.cnf")
}

///|
test "flat50-453.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-453.cnf")
}

///|
test "flat50-233.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-233.cnf")
}

///|
test "flat50-931.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-931.cnf")
}

///|
test "flat50-619.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-619.cnf")
}

///|
test "flat50-285.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-285.cnf")
}

///|
test "flat50-437.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-437.cnf")
}

///|
test "flat50-796.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-796.cnf")
}

///|
test "flat50-928.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-928.cnf")
}

///|
test "flat50-92.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-92.cnf")
}

///|
test "flat50-221.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-221.cnf")
}

///|
test "flat50-294.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-294.cnf")
}

///|
test "flat50-10.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-10.cnf")
}

///|
test "flat50-18.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-18.cnf")
}

///|
test "flat50-396.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-396.cnf")
}

///|
test "flat50-445.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-445.cnf")
}

///|
test "flat50-755.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-755.cnf")
}

///|
test "flat50-697.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-697.cnf")
}

///|
test "flat50-993.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-993.cnf")
}

///|
test "flat50-921.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-921.cnf")
}

///|
test "flat50-512.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-512.cnf")
}

///|
test "flat50-542.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-542.cnf")
}

///|
test "flat50-861.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-861.cnf")
}

///|
test "flat50-8.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-8.cnf")
}

///|
test "flat50-694.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-694.cnf")
}

///|
test "flat50-841.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-841.cnf")
}

///|
test "flat50-719.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-719.cnf")
}

///|
test "flat50-740.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-740.cnf")
}

///|
test "flat50-323.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-323.cnf")
}

///|
test "flat50-146.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-146.cnf")
}

///|
test "flat50-829.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-829.cnf")
}

///|
test "flat50-346.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-346.cnf")
}

///|
test "flat50-764.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-764.cnf")
}

///|
test "flat50-307.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-307.cnf")
}

///|
test "flat50-636.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-636.cnf")
}

///|
test "flat50-641.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-641.cnf")
}

///|
test "flat50-983.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-983.cnf")
}

///|
test "flat50-418.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-418.cnf")
}

///|
test "flat50-22.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-22.cnf")
}

///|
test "flat50-254.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-254.cnf")
}

///|
test "flat50-304.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-304.cnf")
}

///|
test "flat50-140.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-140.cnf")
}

///|
test "flat50-250.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-250.cnf")
}

///|
test "flat50-320.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-320.cnf")
}

///|
test "flat50-824.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-824.cnf")
}

///|
test "flat50-666.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-666.cnf")
}

///|
test "flat50-986.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-986.cnf")
}

///|
test "flat50-615.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-615.cnf")
}

///|
test "flat50-827.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-827.cnf")
}

///|
test "flat50-878.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-878.cnf")
}

///|
test "flat50-390.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-390.cnf")
}

///|
test "flat50-63.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-63.cnf")
}

///|
test "flat50-122.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-122.cnf")
}

///|
test "flat50-607.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-607.cnf")
}

///|
test "flat50-271.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-271.cnf")
}

///|
test "flat50-41.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-41.cnf")
}

///|
test "flat50-749.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-749.cnf")
}

///|
test "flat50-89.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-89.cnf")
}

///|
test "flat50-938.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-938.cnf")
}

///|
test "flat50-5.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-5.cnf")
}

///|
test "flat50-256.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-256.cnf")
}

///|
test "flat50-800.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-800.cnf")
}

///|
test "flat50-393.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-393.cnf")
}

///|
test "flat50-904.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-904.cnf")
}

///|
test "flat50-60.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-60.cnf")
}

///|
test "flat50-111.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-111.cnf")
}

///|
test "flat50-162.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-162.cnf")
}

///|
test "flat50-472.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-472.cnf")
}

///|
test "flat50-299.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-299.cnf")
}

///|
test "flat50-920.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-920.cnf")
}

///|
test "flat50-727.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-727.cnf")
}

///|
test "flat50-66.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-66.cnf")
}

///|
test "flat50-33.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-33.cnf")
}

///|
test "flat50-317.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-317.cnf")
}

///|
test "flat50-218.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-218.cnf")
}

///|
test "flat50-865.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-865.cnf")
}

///|
test "flat50-845.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-845.cnf")
}

///|
test "flat50-435.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-435.cnf")
}

///|
test "flat50-235.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-235.cnf")
}

///|
test "flat50-494.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-494.cnf")
}

///|
test "flat50-476.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-476.cnf")
}

///|
test "flat50-544.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-544.cnf")
}

///|
test "flat50-255.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-255.cnf")
}

///|
test "flat50-113.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-113.cnf")
}

///|
test "flat50-297.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-297.cnf")
}

///|
test "flat50-725.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-725.cnf")
}

///|
test "flat50-655.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-655.cnf")
}

///|
test "flat50-312.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-312.cnf")
}

///|
test "flat50-816.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-816.cnf")
}

///|
test "flat50-941.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-941.cnf")
}

///|
test "flat50-611.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-611.cnf")
}

///|
test "flat50-47.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-47.cnf")
}

///|
test "flat50-960.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-960.cnf")
}

///|
test "flat50-945.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-945.cnf")
}

///|
test "flat50-689.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-689.cnf")
}

///|
test "flat50-652.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-652.cnf")
}

///|
test "flat50-434.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-434.cnf")
}

///|
test "flat50-59.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-59.cnf")
}

///|
test "flat50-750.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-750.cnf")
}

///|
test "flat50-403.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-403.cnf")
}

///|
test "flat50-12.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-12.cnf")
}

///|
test "flat50-497.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-497.cnf")
}

///|
test "flat50-212.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-212.cnf")
}

///|
test "flat50-132.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-132.cnf")
}

///|
test "flat50-610.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-610.cnf")
}

///|
test "flat50-51.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-51.cnf")
}

///|
test "flat50-871.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-871.cnf")
}

///|
test "flat50-477.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-477.cnf")
}

///|
test "flat50-656.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-656.cnf")
}

///|
test "flat50-98.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-98.cnf")
}

///|
test "flat50-127.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-127.cnf")
}

///|
test "flat50-327.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-327.cnf")
}

///|
test "flat50-55.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-55.cnf")
}

///|
test "flat50-767.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-767.cnf")
}

///|
test "flat50-120.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-120.cnf")
}

///|
test "flat50-363.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-363.cnf")
}

///|
test "flat50-11.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-11.cnf")
}

///|
test "flat50-227.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-227.cnf")
}

///|
test "flat50-462.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-462.cnf")
}

///|
test "flat50-522.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-522.cnf")
}

///|
test "flat50-225.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-225.cnf")
}

///|
test "flat50-944.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-944.cnf")
}

///|
test "flat50-551.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-551.cnf")
}

///|
test "flat50-731.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-731.cnf")
}

///|
test "flat50-516.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-516.cnf")
}

///|
test "flat50-901.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-901.cnf")
}

///|
test "flat50-540.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-540.cnf")
}

///|
test "flat50-591.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-591.cnf")
}

///|
test "flat50-194.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-194.cnf")
}

///|
test "flat50-783.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-783.cnf")
}

///|
test "flat50-436.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-436.cnf")
}

///|
test "flat50-366.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-366.cnf")
}

///|
test "flat50-870.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-870.cnf")
}

///|
test "flat50-61.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-61.cnf")
}

///|
test "flat50-837.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-837.cnf")
}

///|
test "flat50-257.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-257.cnf")
}

///|
test "flat50-432.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-432.cnf")
}

///|
test "flat50-806.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-806.cnf")
}

///|
test "flat50-54.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-54.cnf")
}

///|
test "flat50-604.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-604.cnf")
}

///|
test "flat50-804.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-804.cnf")
}

///|
test "flat50-991.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-991.cnf")
}

///|
test "flat50-83.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-83.cnf")
}

///|
test "flat50-509.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-509.cnf")
}

///|
test "flat50-34.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-34.cnf")
}

///|
test "flat50-622.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-622.cnf")
}

///|
test "flat50-200.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-200.cnf")
}

///|
test "flat50-818.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-818.cnf")
}

///|
test "flat50-314.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-314.cnf")
}

///|
test "flat50-389.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-389.cnf")
}

///|
test "flat50-300.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-300.cnf")
}

///|
test "flat50-807.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-807.cnf")
}

///|
test "flat50-402.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-402.cnf")
}

///|
test "flat50-245.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-245.cnf")
}

///|
test "flat50-124.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-124.cnf")
}

///|
test "flat50-838.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-838.cnf")
}

///|
test "flat50-411.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-411.cnf")
}

///|
test "flat50-882.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-882.cnf")
}

///|
test "flat50-833.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-833.cnf")
}

///|
test "flat50-203.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-203.cnf")
}

///|
test "flat50-147.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-147.cnf")
}

///|
test "flat50-621.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-621.cnf")
}

///|
test "flat50-163.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-163.cnf")
}

///|
test "flat50-224.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-224.cnf")
}

///|
test "flat50-444.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-444.cnf")
}

///|
test "flat50-531.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-531.cnf")
}

///|
test "flat50-139.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-139.cnf")
}

///|
test "flat50-175.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-175.cnf")
}

///|
test "flat50-681.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-681.cnf")
}

///|
test "flat50-994.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-994.cnf")
}

///|
test "flat50-751.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-751.cnf")
}

///|
test "flat50-654.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-654.cnf")
}

///|
test "flat50-157.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-157.cnf")
}

///|
test "flat50-324.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-324.cnf")
}

///|
test "flat50-848.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-848.cnf")
}

///|
test "flat50-766.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-766.cnf")
}

///|
test "flat50-399.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-399.cnf")
}

///|
test "flat50-447.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-447.cnf")
}

///|
test "flat50-422.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-422.cnf")
}

///|
test "flat50-454.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-454.cnf")
}

///|
test "flat50-241.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-241.cnf")
}

///|
test "flat50-138.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-138.cnf")
}

///|
test "flat50-409.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-409.cnf")
}

///|
test "flat50-43.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-43.cnf")
}

///|
test "flat50-278.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-278.cnf")
}

///|
test "flat50-709.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-709.cnf")
}

///|
test "flat50-684.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-684.cnf")
}

///|
test "flat50-780.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-780.cnf")
}

///|
test "flat50-788.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-788.cnf")
}

///|
test "flat50-791.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-791.cnf")
}

///|
test "flat50-853.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-853.cnf")
}

///|
test "flat50-2.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-2.cnf")
}

///|
test "flat50-562.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-562.cnf")
}

///|
test "flat50-714.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-714.cnf")
}

///|
test "flat50-178.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-178.cnf")
}

///|
test "flat50-458.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-458.cnf")
}

///|
test "flat50-517.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-517.cnf")
}

///|
test "flat50-779.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-779.cnf")
}

///|
test "flat50-608.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-608.cnf")
}

///|
test "flat50-854.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-854.cnf")
}

///|
test "flat50-259.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-259.cnf")
}

///|
test "flat50-167.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-167.cnf")
}

///|
test "flat50-430.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-430.cnf")
}

///|
test "flat50-349.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-349.cnf")
}

///|
test "flat50-956.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-956.cnf")
}

///|
test "flat50-985.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-985.cnf")
}

///|
test "flat50-408.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-408.cnf")
}

///|
test "flat50-954.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-954.cnf")
}

///|
test "flat50-412.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-412.cnf")
}

///|
test "flat50-624.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-624.cnf")
}

///|
test "flat50-391.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-391.cnf")
}

///|
test "flat50-463.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-463.cnf")
}

///|
test "flat50-378.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-378.cnf")
}

///|
test "flat50-808.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-808.cnf")
}

///|
test "flat50-840.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-840.cnf")
}

///|
test "flat50-644.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-644.cnf")
}

///|
test "flat50-488.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-488.cnf")
}

///|
test "flat50-978.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-978.cnf")
}

///|
test "flat50-375.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-375.cnf")
}

///|
test "flat50-972.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-972.cnf")
}

///|
test "flat50-85.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-85.cnf")
}

///|
test "flat50-776.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-776.cnf")
}

///|
test "flat50-166.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-166.cnf")
}

///|
test "flat50-876.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-876.cnf")
}

///|
test "flat50-374.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-374.cnf")
}

///|
test "flat50-862.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-862.cnf")
}

///|
test "flat50-377.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-377.cnf")
}

///|
test "flat50-532.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-532.cnf")
}

///|
test "flat50-487.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-487.cnf")
}

///|
test "flat50-910.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-910.cnf")
}

///|
test "flat50-913.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-913.cnf")
}

///|
test "flat50-698.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-698.cnf")
}

///|
test "flat50-708.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-708.cnf")
}

///|
test "flat50-152.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-152.cnf")
}

///|
test "flat50-192.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-192.cnf")
}

///|
test "flat50-911.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-911.cnf")
}

///|
test "flat50-345.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-345.cnf")
}

///|
test "flat50-571.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-571.cnf")
}

///|
test "flat50-67.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-67.cnf")
}

///|
test "flat50-342.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-342.cnf")
}

///|
test "flat50-893.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-893.cnf")
}

///|
test "flat50-706.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-706.cnf")
}

///|
test "flat50-961.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-961.cnf")
}

///|
test "flat50-733.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-733.cnf")
}

///|
test "flat50-790.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-790.cnf")
}

///|
test "flat50-486.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-486.cnf")
}

///|
test "flat50-386.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-386.cnf")
}

///|
test "flat50-525.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-525.cnf")
}

///|
test "flat50-953.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-953.cnf")
}

///|
test "flat50-86.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-86.cnf")
}

///|
test "flat50-770.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-770.cnf")
}

///|
test "flat50-609.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-609.cnf")
}

///|
test "flat50-188.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-188.cnf")
}

///|
test "flat50-186.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-186.cnf")
}

///|
test "flat50-129.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-129.cnf")
}

///|
test "flat50-196.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-196.cnf")
}

///|
test "flat50-479.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-479.cnf")
}

///|
test "flat50-662.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-662.cnf")
}

///|
test "flat50-885.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-885.cnf")
}

///|
test "flat50-935.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-935.cnf")
}

///|
test "flat50-846.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-846.cnf")
}

///|
test "flat50-593.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-593.cnf")
}

///|
test "flat50-825.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-825.cnf")
}

///|
test "flat50-504.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-504.cnf")
}

///|
test "flat50-523.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-523.cnf")
}

///|
test "flat50-667.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-667.cnf")
}

///|
test "flat50-665.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-665.cnf")
}

///|
test "flat50-645.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-645.cnf")
}

///|
test "flat50-105.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-105.cnf")
}

///|
test "flat50-866.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-866.cnf")
}

///|
test "flat50-330.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-330.cnf")
}

///|
test "flat50-730.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-730.cnf")
}

///|
test "flat50-880.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-880.cnf")
}

///|
test "flat50-201.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-201.cnf")
}

///|
test "flat50-407.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-407.cnf")
}

///|
test "flat50-333.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-333.cnf")
}

///|
test "flat50-84.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-84.cnf")
}

///|
test "flat50-277.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-277.cnf")
}

///|
test "flat50-964.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-964.cnf")
}

///|
test "flat50-701.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-701.cnf")
}

///|
test "flat50-912.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-912.cnf")
}

///|
test "flat50-737.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-737.cnf")
}

///|
test "flat50-932.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-932.cnf")
}

///|
test "flat50-102.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-102.cnf")
}

///|
test "flat50-855.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-855.cnf")
}

///|
test "flat50-683.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-683.cnf")
}

///|
test "flat50-473.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-473.cnf")
}

///|
test "flat50-459.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-459.cnf")
}

///|
test "flat50-421.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-421.cnf")
}

///|
test "flat50-248.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-248.cnf")
}

///|
test "flat50-118.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-118.cnf")
}

///|
test "flat50-670.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-670.cnf")
}

///|
test "flat50-155.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-155.cnf")
}

///|
test "flat50-988.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-988.cnf")
}

///|
test "flat50-164.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-164.cnf")
}

///|
test "flat50-357.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-357.cnf")
}

///|
test "flat50-533.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-533.cnf")
}

///|
test "flat50-496.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-496.cnf")
}

///|
test "flat50-588.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-588.cnf")
}

///|
test "flat50-958.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-958.cnf")
}

///|
test "flat50-215.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-215.cnf")
}

///|
test "flat50-185.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-185.cnf")
}

///|
test "flat50-492.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-492.cnf")
}

///|
test "flat50-334.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-334.cnf")
}

///|
test "flat50-849.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-849.cnf")
}

///|
test "flat50-429.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-429.cnf")
}

///|
test "flat50-439.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-439.cnf")
}

///|
test "flat50-441.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-441.cnf")
}

///|
test "flat50-894.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-894.cnf")
}

///|
test "flat50-112.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-112.cnf")
}

///|
test "flat50-416.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-416.cnf")
}

///|
test "flat50-313.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-313.cnf")
}

///|
test "flat50-289.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-289.cnf")
}

///|
test "flat50-798.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-798.cnf")
}

///|
test "flat50-505.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-505.cnf")
}

///|
test "flat50-519.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-519.cnf")
}

///|
test "flat50-171.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-171.cnf")
}

///|
test "flat50-515.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-515.cnf")
}

///|
test "flat50-249.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-249.cnf")
}

///|
test "flat50-193.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-193.cnf")
}

///|
test "flat50-381.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-381.cnf")
}

///|
test "flat50-471.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-471.cnf")
}

///|
test "flat50-9.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-9.cnf")
}

///|
test "flat50-14.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-14.cnf")
}

///|
test "flat50-242.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-242.cnf")
}

///|
test "flat50-198.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-198.cnf")
}

///|
test "flat50-835.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-835.cnf")
}

///|
test "flat50-673.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-673.cnf")
}

///|
test "flat50-467.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-467.cnf")
}

///|
test "flat50-914.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-914.cnf")
}

///|
test "flat50-240.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-240.cnf")
}

///|
test "flat50-795.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-795.cnf")
}

///|
test "flat50-295.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-295.cnf")
}

///|
test "flat50-325.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-325.cnf")
}

///|
test "flat50-550.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-550.cnf")
}

///|
test "flat50-182.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-182.cnf")
}

///|
test "flat50-427.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-427.cnf")
}

///|
test "flat50-443.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-443.cnf")
}

///|
test "flat50-999.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-999.cnf")
}

///|
test "flat50-272.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-272.cnf")
}

///|
test "flat50-332.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-332.cnf")
}

///|
test "flat50-126.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-126.cnf")
}

///|
test "flat50-653.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-653.cnf")
}

///|
test "flat50-457.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-457.cnf")
}

///|
test "flat50-585.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-585.cnf")
}

///|
test "flat50-13.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-13.cnf")
}

///|
test "flat50-664.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-664.cnf")
}

///|
test "flat50-199.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-199.cnf")
}

///|
test "flat50-952.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-952.cnf")
}

///|
test "flat50-716.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-716.cnf")
}

///|
test "flat50-20.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-20.cnf")
}

///|
test "flat50-107.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-107.cnf")
}

///|
test "flat50-535.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-535.cnf")
}

///|
test "flat50-406.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-406.cnf")
}

///|
test "flat50-742.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-742.cnf")
}

///|
test "flat50-474.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-474.cnf")
}

///|
test "flat50-223.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-223.cnf")
}

///|
test "flat50-184.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-184.cnf")
}

///|
test "flat50-757.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-757.cnf")
}

///|
test "flat50-883.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-883.cnf")
}

///|
test "flat50-79.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-79.cnf")
}

///|
test "flat50-971.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-971.cnf")
}

///|
test "flat50-844.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-844.cnf")
}

///|
test "flat50-106.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-106.cnf")
}

///|
test "flat50-939.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-939.cnf")
}

///|
test "flat50-877.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-877.cnf")
}

///|
test "flat50-423.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-423.cnf")
}

///|
test "flat50-263.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-263.cnf")
}

///|
test "flat50-809.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-809.cnf")
}

///|
test "flat50-238.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-238.cnf")
}

///|
test "flat50-15.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-15.cnf")
}

///|
test "flat50-40.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-40.cnf")
}

///|
test "flat50-150.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-150.cnf")
}

///|
test "flat50-924.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-924.cnf")
}

///|
test "flat50-900.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-900.cnf")
}

///|
test "flat50-247.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-247.cnf")
}

///|
test "flat50-75.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-75.cnf")
}

///|
test "flat50-78.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-78.cnf")
}

///|
test "flat50-290.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-290.cnf")
}

///|
test "flat50-65.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-65.cnf")
}

///|
test "flat50-210.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-210.cnf")
}

///|
test "flat50-560.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-560.cnf")
}

///|
test "flat50-828.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-828.cnf")
}

///|
test "flat50-570.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-570.cnf")
}

///|
test "flat50-442.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-442.cnf")
}

///|
test "flat50-965.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-965.cnf")
}

///|
test "flat50-287.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-287.cnf")
}

///|
test "flat50-137.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-137.cnf")
}

///|
test "flat50-309.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-309.cnf")
}

///|
test "flat50-351.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-351.cnf")
}

///|
test "flat50-618.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-618.cnf")
}

///|
test "flat50-873.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-873.cnf")
}

///|
test "flat50-371.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-371.cnf")
}

///|
test "flat50-907.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-907.cnf")
}

///|
test "flat50-568.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-568.cnf")
}

///|
test "flat50-687.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-687.cnf")
}

///|
test "flat50-385.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-385.cnf")
}

///|
test "flat50-114.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-114.cnf")
}

///|
test "flat50-957.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-957.cnf")
}

///|
test "flat50-101.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-101.cnf")
}

///|
test "flat50-425.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-425.cnf")
}

///|
test "flat50-87.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-87.cnf")
}

///|
test "flat50-576.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-576.cnf")
}

///|
test "flat50-413.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-413.cnf")
}

///|
test "flat50-530.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-530.cnf")
}

///|
test "flat50-704.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-704.cnf")
}

///|
test "flat50-265.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-265.cnf")
}

///|
test "flat50-908.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-908.cnf")
}

///|
test "flat50-141.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-141.cnf")
}

///|
test "flat50-553.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-553.cnf")
}

///|
test "flat50-302.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-302.cnf")
}

///|
test "flat50-244.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-244.cnf")
}

///|
test "flat50-431.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-431.cnf")
}

///|
test "flat50-549.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-549.cnf")
}

///|
test "flat50-787.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-787.cnf")
}

///|
test "flat50-276.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-276.cnf")
}

///|
test "flat50-933.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-933.cnf")
}

///|
test "flat50-552.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-552.cnf")
}

///|
test "flat50-258.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-258.cnf")
}

///|
test "flat50-373.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-373.cnf")
}

///|
test "flat50-721.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-721.cnf")
}

///|
test "flat50-734.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-734.cnf")
}

///|
test "flat50-169.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-169.cnf")
}

///|
test "flat50-234.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-234.cnf")
}

///|
test "flat50-82.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-82.cnf")
}

///|
test "flat50-484.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-484.cnf")
}

///|
test "flat50-569.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-569.cnf")
}

///|
test "flat50-311.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-311.cnf")
}

///|
test "flat50-597.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-597.cnf")
}

///|
test "flat50-365.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-365.cnf")
}

///|
test "flat50-119.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-119.cnf")
}

///|
test "flat50-246.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-246.cnf")
}

///|
test "flat50-172.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-172.cnf")
}

///|
test "flat50-821.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-821.cnf")
}

///|
test "flat50-661.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-661.cnf")
}

///|
test "flat50-802.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-802.cnf")
}

///|
test "flat50-156.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-156.cnf")
}

///|
test "flat50-189.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-189.cnf")
}

///|
test "flat50-650.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-650.cnf")
}

///|
test "flat50-817.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-817.cnf")
}

///|
test "flat50-989.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-989.cnf")
}

///|
test "flat50-612.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-612.cnf")
}

///|
test "flat50-433.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-433.cnf")
}

///|
test "flat50-32.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-32.cnf")
}

///|
test "flat50-96.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-96.cnf")
}

///|
test "flat50-556.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-556.cnf")
}

///|
test "flat50-715.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-715.cnf")
}

///|
test "flat50-897.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-897.cnf")
}

///|
test "flat50-48.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-48.cnf")
}

///|
test "flat50-367.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-367.cnf")
}

///|
test "flat50-148.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-148.cnf")
}

///|
test "flat50-369.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-369.cnf")
}

///|
test "flat50-703.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-703.cnf")
}

///|
test "flat50-279.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-279.cnf")
}

///|
test "flat50-338.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-338.cnf")
}

///|
test "flat50-722.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-722.cnf")
}

///|
test "flat50-376.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-376.cnf")
}

///|
test "flat50-62.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-62.cnf")
}

///|
test "flat50-405.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-405.cnf")
}

///|
test "flat50-775.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-775.cnf")
}

///|
test "flat50-125.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-125.cnf")
}

///|
test "flat50-466.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-466.cnf")
}

///|
test "flat50-634.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-634.cnf")
}

///|
test "flat50-58.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-58.cnf")
}

///|
test "flat50-982.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-982.cnf")
}

///|
test "flat50-942.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-942.cnf")
}

///|
test "flat50-214.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-214.cnf")
}

///|
test "flat50-207.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-207.cnf")
}

///|
test "flat50-959.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-959.cnf")
}

///|
test "flat50-955.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-955.cnf")
}

///|
test "flat50-35.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-35.cnf")
}

///|
test "flat50-726.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-726.cnf")
}

///|
test "flat50-284.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-284.cnf")
}

///|
test "flat50-782.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-782.cnf")
}

///|
test "flat50-340.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-340.cnf")
}

///|
test "flat50-990.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-990.cnf")
}

///|
test "flat50-686.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-686.cnf")
}

///|
test "flat50-695.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-695.cnf")
}

///|
test "flat50-812.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-812.cnf")
}

///|
test "flat50-128.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-128.cnf")
}

///|
test "flat50-992.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-992.cnf")
}

///|
test "flat50-70.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-70.cnf")
}

///|
test "flat50-448.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-448.cnf")
}

///|
test "flat50-356.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-356.cnf")
}

///|
test "flat50-739.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-739.cnf")
}

///|
test "flat50-598.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-598.cnf")
}

///|
test "flat50-649.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-649.cnf")
}

///|
test "flat50-563.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-563.cnf")
}

///|
test "flat50-632.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-632.cnf")
}

///|
test "flat50-969.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-969.cnf")
}

///|
test "flat50-213.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-213.cnf")
}

///|
test "flat50-380.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-380.cnf")
}

///|
test "flat50-651.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-651.cnf")
}

///|
test "flat50-275.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-275.cnf")
}

///|
test "flat50-685.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-685.cnf")
}

///|
test "flat50-415.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-415.cnf")
}

///|
test "flat50-491.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-491.cnf")
}

///|
test "flat50-426.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-426.cnf")
}

///|
test "flat50-239.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-239.cnf")
}

///|
test "flat50-834.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-834.cnf")
}

///|
test "flat50-206.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-206.cnf")
}

///|
test "flat50-693.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-693.cnf")
}

///|
test "flat50-99.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-99.cnf")
}

///|
test "flat50-209.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-209.cnf")
}

///|
test "flat50-555.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-555.cnf")
}

///|
test "flat50-202.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-202.cnf")
}

///|
test "flat50-117.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-117.cnf")
}

///|
test "flat50-104.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-104.cnf")
}

///|
test "flat50-613.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-613.cnf")
}

///|
test "flat50-232.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-232.cnf")
}

///|
test "flat50-543.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-543.cnf")
}

///|
test "flat50-781.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-781.cnf")
}

///|
test "flat50-410.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-410.cnf")
}

///|
test "flat50-785.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-785.cnf")
}

///|
test "flat50-929.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-929.cnf")
}

///|
test "flat50-567.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-567.cnf")
}

///|
test "flat50-926.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-926.cnf")
}

///|
test "flat50-674.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-674.cnf")
}

///|
test "flat50-506.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-506.cnf")
}

///|
test "flat50-646.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-646.cnf")
}

///|
test "flat50-23.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-23.cnf")
}

///|
test "flat50-498.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-498.cnf")
}

///|
test "flat50-77.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-77.cnf")
}

///|
test "flat50-601.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-601.cnf")
}

///|
test "flat50-984.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-984.cnf")
}

///|
test "flat50-269.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-269.cnf")
}

///|
test "flat50-967.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-967.cnf")
}

///|
test "flat50-38.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-38.cnf")
}

///|
test "flat50-606.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-606.cnf")
}

///|
test "flat50-482.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-482.cnf")
}

///|
test "flat50-682.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-682.cnf")
}

///|
test "flat50-197.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-197.cnf")
}

///|
test "flat50-794.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-794.cnf")
}

///|
test "flat50-934.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-934.cnf")
}

///|
test "flat50-705.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-705.cnf")
}

///|
test "flat50-72.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-72.cnf")
}

///|
test "flat50-93.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-93.cnf")
}

///|
test "flat50-678.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-678.cnf")
}

///|
test "flat50-524.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-524.cnf")
}

///|
test "flat50-26.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-26.cnf")
}

///|
test "flat50-510.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-510.cnf")
}

///|
test "flat50-754.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-754.cnf")
}

///|
test "flat50-995.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-995.cnf")
}

///|
test "flat50-623.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-623.cnf")
}

///|
test "flat50-424.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-424.cnf")
}

///|
test "flat50-744.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-744.cnf")
}

///|
test "flat50-262.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-262.cnf")
}

///|
test "flat50-743.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-743.cnf")
}

///|
test "flat50-925.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-925.cnf")
}

///|
test "flat50-144.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-144.cnf")
}

///|
test "flat50-786.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-786.cnf")
}

///|
test "flat50-173.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-173.cnf")
}

///|
test "flat50-27.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-27.cnf")
}

///|
test "flat50-153.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-153.cnf")
}

///|
test "flat50-979.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-979.cnf")
}

///|
test "flat50-45.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-45.cnf")
}

///|
test "flat50-116.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-116.cnf")
}

///|
test "flat50-675.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-675.cnf")
}

///|
test "flat50-826.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-826.cnf")
}

///|
test "flat50-455.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-455.cnf")
}

///|
test "flat50-308.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-308.cnf")
}

///|
test "flat50-253.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-253.cnf")
}

///|
test "flat50-950.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-950.cnf")
}

///|
test "flat50-987.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-987.cnf")
}

///|
test "flat50-177.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-177.cnf")
}

///|
test "flat50-485.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-485.cnf")
}

///|
test "flat50-183.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-183.cnf")
}

///|
test "flat50-438.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-438.cnf")
}

///|
test "flat50-732.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-732.cnf")
}

///|
test "flat50-668.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-668.cnf")
}

///|
test "flat50-145.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-145.cnf")
}

///|
test "flat50-1.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-1.cnf")
}

///|
test "flat50-268.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-268.cnf")
}

///|
test "flat50-599.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-599.cnf")
}

///|
test "flat50-69.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-69.cnf")
}

///|
test "flat50-37.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-37.cnf")
}

///|
test "flat50-19.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-19.cnf")
}

///|
test "flat50-792.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-792.cnf")
}

///|
test "flat50-511.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-511.cnf")
}

///|
test "flat50-527.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-527.cnf")
}

///|
test "flat50-839.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-839.cnf")
}

///|
test "flat50-180.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-180.cnf")
}

///|
test "flat50-968.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-968.cnf")
}

///|
test "flat50-361.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-361.cnf")
}

///|
test "flat50-717.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-717.cnf")
}

///|
test "flat50-115.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-115.cnf")
}

///|
test "flat50-368.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-368.cnf")
}

///|
test "flat50-639.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-639.cnf")
}

///|
test "flat50-738.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-738.cnf")
}

///|
test "flat50-362.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-362.cnf")
}

///|
test "flat50-940.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-940.cnf")
}

///|
test "flat50-88.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-88.cnf")
}

///|
test "flat50-266.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-266.cnf")
}

///|
test "flat50-707.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-707.cnf")
}

///|
test "flat50-465.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-465.cnf")
}

///|
test "flat50-335.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-335.cnf")
}

///|
test "flat50-943.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-943.cnf")
}

///|
test "flat50-905.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-905.cnf")
}

///|
test "flat50-91.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-91.cnf")
}

///|
test "flat50-891.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-891.cnf")
}

///|
test "flat50-637.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-637.cnf")
}

///|
test "flat50-56.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-56.cnf")
}

///|
test "flat50-582.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-582.cnf")
}

///|
test "flat50-25.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-25.cnf")
}

///|
test "flat50-108.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-108.cnf")
}

///|
test "flat50-336.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-336.cnf")
}

///|
test "flat50-718.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-718.cnf")
}

///|
test "flat50-158.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-158.cnf")
}

///|
test "flat50-31.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-31.cnf")
}

///|
test "flat50-852.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-852.cnf")
}

///|
test "flat50-329.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-329.cnf")
}

///|
test "flat50-536.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-536.cnf")
}

///|
test "flat50-179.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-179.cnf")
}

///|
test "flat50-886.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-886.cnf")
}

///|
test "flat50-760.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-760.cnf")
}

///|
test "flat50-973.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-973.cnf")
}

///|
test "flat50-874.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-874.cnf")
}

///|
test "flat50-565.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-565.cnf")
}

///|
test "flat50-629.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-629.cnf")
}

///|
test "flat50-677.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-677.cnf")
}

///|
test "flat50-872.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-872.cnf")
}

///|
test "flat50-741.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-741.cnf")
}

///|
test "flat50-594.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-594.cnf")
}

///|
test "flat50-103.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-103.cnf")
}

///|
test "flat50-343.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-343.cnf")
}

///|
test "flat50-195.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-195.cnf")
}

///|
test "flat50-603.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-603.cnf")
}

///|
test "flat50-322.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-322.cnf")
}

///|
test "flat50-658.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-658.cnf")
}

///|
test "flat50-895.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-895.cnf")
}

///|
test "flat50-887.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-887.cnf")
}

///|
test "flat50-130.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-130.cnf")
}

///|
test "flat50-642.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-642.cnf")
}

///|
test "flat50-559.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-559.cnf")
}

///|
test "flat50-42.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-42.cnf")
}

///|
test "flat50-888.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-888.cnf")
}

///|
test "flat50-763.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-763.cnf")
}

///|
test "flat50-626.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-626.cnf")
}

///|
test "flat50-383.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-383.cnf")
}

///|
test "flat50-916.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-916.cnf")
}

///|
test "flat50-702.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-702.cnf")
}

///|
test "flat50-21.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-21.cnf")
}

///|
test "flat50-823.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-823.cnf")
}

///|
test "flat50-161.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-161.cnf")
}

///|
test "flat50-863.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-863.cnf")
}

///|
test "flat50-159.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-159.cnf")
}

///|
test "flat50-217.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-217.cnf")
}

///|
test "flat50-305.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-305.cnf")
}

///|
test "flat50-892.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-892.cnf")
}

///|
test "flat50-769.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-769.cnf")
}

///|
test "flat50-121.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-121.cnf")
}

///|
test "flat50-881.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-881.cnf")
}

///|
test "flat50-123.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-123.cnf")
}

///|
test "flat50-298.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-298.cnf")
}

///|
test "flat50-501.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-501.cnf")
}

///|
test "flat50-331.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-331.cnf")
}

///|
test "flat50-772.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-772.cnf")
}

///|
test "flat50-724.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-724.cnf")
}

///|
test "flat50-587.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-587.cnf")
}

///|
test "flat50-558.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-558.cnf")
}

///|
test "flat50-394.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-394.cnf")
}

///|
test "flat50-489.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-489.cnf")
}

///|
test "flat50-801.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-801.cnf")
}

///|
test "flat50-80.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-80.cnf")
}

///|
test "flat50-4.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-4.cnf")
}

///|
test "flat50-534.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-534.cnf")
}

///|
test "flat50-301.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-301.cnf")
}

///|
test "flat50-319.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-319.cnf")
}

///|
test "flat50-286.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-286.cnf")
}

///|
test "flat50-541.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-541.cnf")
}

///|
test "flat50-461.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-461.cnf")
}

///|
test "flat50-176.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-176.cnf")
}

///|
test "flat50-6.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-6.cnf")
}

///|
test "flat50-267.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-267.cnf")
}

///|
test "flat50-917.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-917.cnf")
}

///|
test "flat50-292.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-292.cnf")
}

///|
test "flat50-574.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-574.cnf")
}

///|
test "flat50-379.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-379.cnf")
}

///|
test "flat50-372.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-372.cnf")
}

///|
test "flat50-353.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-353.cnf")
}

///|
test "flat50-17.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-17.cnf")
}

///|
test "flat50-222.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-222.cnf")
}

///|
test "flat50-676.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-676.cnf")
}

///|
test "flat50-354.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-354.cnf")
}

///|
test "flat50-581.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-581.cnf")
}

///|
test "flat50-237.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-237.cnf")
}

///|
test "flat50-815.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-815.cnf")
}

///|
test "flat50-49.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-49.cnf")
}

///|
test "flat50-962.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-962.cnf")
}

///|
test "flat50-545.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-545.cnf")
}

///|
test "flat50-671.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-671.cnf")
}

///|
test "flat50-500.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-500.cnf")
}

///|
test "flat50-273.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-273.cnf")
}

///|
test "flat50-521.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-521.cnf")
}

///|
test "flat50-628.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-628.cnf")
}

///|
test "flat50-660.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-660.cnf")
}

///|
test "flat50-493.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-493.cnf")
}

///|
test "flat50-573.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-573.cnf")
}

///|
test "flat50-590.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-590.cnf")
}

///|
test "flat50-595.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-595.cnf")
}

///|
test "flat50-251.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-251.cnf")
}

///|
test "flat50-890.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-890.cnf")
}

///|
test "flat50-771.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-771.cnf")
}

///|
test "flat50-230.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-230.cnf")
}

///|
test "flat50-191.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-191.cnf")
}

///|
test "flat50-283.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-283.cnf")
}

///|
test "flat50-635.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-635.cnf")
}

///|
test "flat50-142.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-142.cnf")
}

///|
test "flat50-143.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-143.cnf")
}

///|
test "flat50-843.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-843.cnf")
}

///|
test "flat50-401.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-401.cnf")
}

///|
test "flat50-946.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-946.cnf")
}

///|
test "flat50-483.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-483.cnf")
}

///|
test "flat50-857.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-857.cnf")
}

///|
test "flat50-81.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-81.cnf")
}

///|
test "flat50-468.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-468.cnf")
}

///|
test "flat50-446.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-446.cnf")
}

///|
test "flat50-261.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-261.cnf")
}

///|
test "flat50-774.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-774.cnf")
}

///|
test "flat50-360.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-360.cnf")
}

///|
test "flat50-219.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-219.cnf")
}

///|
test "flat50-902.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-902.cnf")
}

///|
test "flat50-94.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-94.cnf")
}

///|
test "flat50-643.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-643.cnf")
}

///|
test "flat50-922.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-922.cnf")
}

///|
test "flat50-690.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-690.cnf")
}

///|
test "flat50-316.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-316.cnf")
}

///|
test "flat50-858.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-858.cnf")
}

///|
test "flat50-395.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-395.cnf")
}

///|
test "flat50-211.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-211.cnf")
}

///|
test "flat50-605.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-605.cnf")
}

///|
test "flat50-832.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-832.cnf")
}

///|
test "flat50-187.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-187.cnf")
}

///|
test "flat50-529.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-529.cnf")
}

///|
test "flat50-470.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-470.cnf")
}

///|
test "flat50-296.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-296.cnf")
}

///|
test "flat50-909.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-909.cnf")
}

///|
test "flat50-355.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-355.cnf")
}

///|
test "flat50-869.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-869.cnf")
}

///|
test "flat50-723.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-723.cnf")
}

///|
test "flat50-50.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-50.cnf")
}

///|
test "flat50-400.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-400.cnf")
}

///|
test "flat50-39.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-39.cnf")
}

///|
test "flat50-350.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-350.cnf")
}

///|
test "flat50-270.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-270.cnf")
}

///|
test "flat50-850.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-850.cnf")
}

///|
test "flat50-174.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-174.cnf")
}

///|
test "flat50-205.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-205.cnf")
}

///|
test "flat50-930.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-930.cnf")
}

///|
test "flat50-546.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-546.cnf")
}

///|
test "flat50-976.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-976.cnf")
}

///|
test "flat50-16.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-16.cnf")
}

///|
test "flat50-518.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-518.cnf")
}

///|
test "flat50-784.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-784.cnf")
}

///|
test "flat50-328.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-328.cnf")
}

///|
test "flat50-768.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-768.cnf")
}

///|
test "flat50-729.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-729.cnf")
}

///|
test "flat50-602.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-602.cnf")
}

///|
test "flat50-836.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-836.cnf")
}

///|
test "flat50-799.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-799.cnf")
}

///|
test "flat50-631.cnf" {
  check_sat("./dimacs/flat50v115e/flat50-631.cnf")
}
