///|
test "uf20-0519.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0519.cnf")
}

///|
test "uf20-0710.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0710.cnf")
}

///|
test "uf20-0487.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0487.cnf")
}

///|
test "uf20-0555.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0555.cnf")
}

///|
test "uf20-0153.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0153.cnf")
}

///|
test "uf20-054.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-054.cnf")
}

///|
test "uf20-058.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-058.cnf")
}

///|
test "uf20-0103.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0103.cnf")
}

///|
test "uf20-0899.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0899.cnf")
}

///|
test "uf20-0743.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0743.cnf")
}

///|
test "uf20-0490.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0490.cnf")
}

///|
test "uf20-027.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-027.cnf")
}

///|
test "uf20-0216.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0216.cnf")
}

///|
test "uf20-0495.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0495.cnf")
}

///|
test "uf20-039.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-039.cnf")
}

///|
test "uf20-075.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-075.cnf")
}

///|
test "uf20-0779.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0779.cnf")
}

///|
test "uf20-0253.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0253.cnf")
}

///|
test "uf20-0957.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0957.cnf")
}

///|
test "uf20-0945.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0945.cnf")
}

///|
test "uf20-0967.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0967.cnf")
}

///|
test "uf20-0676.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0676.cnf")
}

///|
test "uf20-0652.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0652.cnf")
}

///|
test "uf20-0284.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0284.cnf")
}

///|
test "uf20-0466.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0466.cnf")
}

///|
test "uf20-0816.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0816.cnf")
}

///|
test "uf20-0691.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0691.cnf")
}

///|
test "uf20-04.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-04.cnf")
}

///|
test "uf20-0168.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0168.cnf")
}

///|
test "uf20-0472.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0472.cnf")
}

///|
test "uf20-0548.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0548.cnf")
}

///|
test "uf20-0697.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0697.cnf")
}
//

///|
test "uf20-0265.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0265.cnf")
}

///|
test "uf20-0711.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0711.cnf")
}

///|
test "uf20-0114.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0114.cnf")
}

///|
test "uf20-0552.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0552.cnf")
}

///|
test "uf20-079.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-079.cnf")
}

///|
test "uf20-0494.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0494.cnf")
}

///|
test "uf20-0157.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0157.cnf")
}

///|
test "uf20-0716.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0716.cnf")
}

///|
test "uf20-095.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-095.cnf")
}

///|
test "uf20-0310.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0310.cnf")
}

///|
test "uf20-0115.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0115.cnf")
}

///|
test "uf20-0450.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0450.cnf")
}

///|
test "uf20-0172.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0172.cnf")
}

///|
test "uf20-0288.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0288.cnf")
}

///|
test "uf20-0978.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0978.cnf")
}

///|
test "uf20-0257.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0257.cnf")
}

///|
test "uf20-0677.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0677.cnf")
}

///|
test "uf20-0758.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0758.cnf")
}

///|
test "uf20-0394.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0394.cnf")
}

///|
test "uf20-0489.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0489.cnf")
}

///|
test "uf20-0771.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0771.cnf")
}

///|
test "uf20-0817.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0817.cnf")
}

///|
test "uf20-0869.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0869.cnf")
}

///|
test "uf20-0242.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0242.cnf")
}

///|
test "uf20-0529.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0529.cnf")
}

///|
test "uf20-0962.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0962.cnf")
}

///|
test "uf20-0918.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0918.cnf")
}

///|
test "uf20-0229.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0229.cnf")
}

///|
test "uf20-0458.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0458.cnf")
}

///|
test "uf20-0804.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0804.cnf")
}

///|
test "uf20-0737.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0737.cnf")
}

///|
test "uf20-0480.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0480.cnf")
}
//

///|
test "uf20-0654.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0654.cnf")
}
//

///|
test "uf20-032.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-032.cnf")
}
//

///|
test "uf20-0880.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0880.cnf")
}
//

///|
test "uf20-0414.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0414.cnf")
}
//

///|
test "uf20-0401.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0401.cnf")
}
//

///|
test "uf20-090.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-090.cnf")
}
//

///|
test "uf20-0267.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0267.cnf")
}
//

///|
test "uf20-0645.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0645.cnf")
}

///|
test "uf20-0202.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0202.cnf")
}

///|
test "uf20-0382.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0382.cnf")
}
//

///|
test "uf20-0199.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0199.cnf")
}
//

///|
test "uf20-0611.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0611.cnf")
}
//

///|
test "uf20-0328.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0328.cnf")
}
//

///|
test "uf20-0390.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0390.cnf")
}
//

///|
test "uf20-0181.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0181.cnf")
}
//

///|
test "uf20-0595.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0595.cnf")
}
//

///|
test "uf20-0610.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0610.cnf")
}
//

///|
test "uf20-0203.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0203.cnf")
}
//

///|
test "uf20-0187.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0187.cnf")
}
//

///|
test "uf20-0428.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0428.cnf")
}
//

///|
test "uf20-0179.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0179.cnf")
}
//

///|
test "uf20-0154.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0154.cnf")
}
//

///|
test "uf20-0702.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0702.cnf")
}
//

///|
test "uf20-0322.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0322.cnf")
}
//

///|
test "uf20-0965.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0965.cnf")
}
//

///|
test "uf20-0629.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0629.cnf")
}
//

///|
test "uf20-0208.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0208.cnf")
}
//

///|
test "uf20-0232.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0232.cnf")
}
//

///|
test "uf20-0249.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0249.cnf")
}
//

///|
test "uf20-0561.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0561.cnf")
}
//

///|
test "uf20-0903.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0903.cnf")
}
//

///|
test "uf20-0757.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0757.cnf")
}
//

///|
test "uf20-0407.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0407.cnf")
}
//

///|
test "uf20-0726.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0726.cnf")
}
//

///|
test "uf20-084.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-084.cnf")
}
//

///|
test "uf20-0170.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0170.cnf")
}
//

///|
test "uf20-0530.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0530.cnf")
}
//

///|
test "uf20-0898.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0898.cnf")
}

///|
test "uf20-0739.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0739.cnf")
}

///|
test "uf20-0150.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0150.cnf")
}
//

///|
test "uf20-042.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-042.cnf")
}
//

///|
test "uf20-0415.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0415.cnf")
}
//

///|
test "uf20-0169.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0169.cnf")
}
//

///|
test "uf20-0374.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0374.cnf")
}
//

///|
test "uf20-099.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-099.cnf")
}
//

///|
test "uf20-0854.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0854.cnf")
}

///|
test "uf20-0568.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0568.cnf")
}

///|
test "uf20-0624.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0624.cnf")
}
//

///|
test "uf20-0849.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0849.cnf")
}
//

///|
test "uf20-0732.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0732.cnf")
}
//

///|
test "uf20-0136.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0136.cnf")
}
//

///|
test "uf20-0889.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0889.cnf")
}
//

///|
test "uf20-0254.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0254.cnf")
}
//

///|
test "uf20-0587.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0587.cnf")
}
//

///|
test "uf20-0417.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0417.cnf")
}
//

///|
test "uf20-0917.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0917.cnf")
}

///|
test "uf20-0146.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0146.cnf")
}

///|
test "uf20-0680.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0680.cnf")
}
//

///|
test "uf20-0634.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0634.cnf")
}
//

///|
test "uf20-0736.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0736.cnf")
}
//

///|
test "uf20-0959.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0959.cnf")
}
//

///|
test "uf20-025.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-025.cnf")
}
//

///|
test "uf20-0196.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0196.cnf")
}
//

///|
test "uf20-0679.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0679.cnf")
}
//

///|
test "uf20-073.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-073.cnf")
}
//

///|
test "uf20-0932.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0932.cnf")
}
//

///|
test "uf20-0935.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0935.cnf")
}
//

///|
test "uf20-0892.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0892.cnf")
}
//

///|
test "uf20-0553.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0553.cnf")
}
//

///|
test "uf20-0643.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0643.cnf")
}
//

///|
test "uf20-096.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-096.cnf")
}

///|
test "uf20-0513.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0513.cnf")
}
//

///|
test "uf20-0964.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0964.cnf")
}
//

///|
test "uf20-0325.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0325.cnf")
}
//

///|
test "uf20-053.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-053.cnf")
}
//

///|
test "uf20-0574.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0574.cnf")
}
//

///|
test "uf20-050.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-050.cnf")
}
//

///|
test "uf20-0468.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0468.cnf")
}
//

///|
test "uf20-0497.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0497.cnf")
}
//

///|
test "uf20-0297.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0297.cnf")
}
//

///|
test "uf20-0994.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0994.cnf")
}

///|
test "uf20-072.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-072.cnf")
}

///|
test "uf20-01.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-01.cnf")
}
//

///|
test "uf20-0852.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0852.cnf")
}
//

///|
test "uf20-028.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-028.cnf")
}
//

///|
test "uf20-0569.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0569.cnf")
}
//

///|
test "uf20-0141.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0141.cnf")
}
//

///|
test "uf20-0135.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0135.cnf")
}
//

///|
test "uf20-0581.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0581.cnf")
}
//

///|
test "uf20-0720.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0720.cnf")
}
//

///|
test "uf20-0332.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0332.cnf")
}
//

///|
test "uf20-0163.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0163.cnf")
}
//

///|
test "uf20-0102.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0102.cnf")
}
//

///|
test "uf20-0619.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0619.cnf")
}
//

///|
test "uf20-0768.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0768.cnf")
}

///|
test "uf20-0833.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0833.cnf")
}
//

///|
test "uf20-0125.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0125.cnf")
}
//

///|
test "uf20-0120.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0120.cnf")
}
//

///|
test "uf20-0902.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0902.cnf")
}
//

///|
test "uf20-0416.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0416.cnf")
}
//

///|
test "uf20-0802.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0802.cnf")
}
//

///|
test "uf20-0914.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0914.cnf")
}
//

///|
test "uf20-0398.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0398.cnf")
}
//

///|
test "uf20-0656.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0656.cnf")
}
//

///|
test "uf20-0399.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0399.cnf")
}
//

///|
test "uf20-0937.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0937.cnf")
}
//

///|
test "uf20-0524.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0524.cnf")
}
//

///|
test "uf20-0754.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0754.cnf")
}

///|
test "uf20-089.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-089.cnf")
}

///|
test "uf20-0829.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0829.cnf")
}
//

///|
test "uf20-0543.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0543.cnf")
}

///|
test "uf20-0173.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0173.cnf")
}

///|
test "uf20-0788.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0788.cnf")
}
//

///|
test "uf20-0708.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0708.cnf")
}
//

///|
test "uf20-0706.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0706.cnf")
}
//

///|
test "uf20-0386.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0386.cnf")
}
//

///|
test "uf20-0851.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0851.cnf")
}
//

///|
test "uf20-0515.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0515.cnf")
}
//

///|
test "uf20-0123.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0123.cnf")
}
//

///|
test "uf20-0525.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0525.cnf")
}

///|
test "uf20-0177.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0177.cnf")
}

///|
test "uf20-0338.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0338.cnf")
}
//

///|
test "uf20-029.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-029.cnf")
}
//

///|
test "uf20-0140.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0140.cnf")
}
//

///|
test "uf20-0496.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0496.cnf")
}
//

///|
test "uf20-0198.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0198.cnf")
}
//

///|
test "uf20-0222.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0222.cnf")
}
//

///|
test "uf20-0303.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0303.cnf")
}
//

///|
test "uf20-0872.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0872.cnf")
}
//

///|
test "uf20-0405.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0405.cnf")
}
//

///|
test "uf20-0139.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0139.cnf")
}
//

///|
test "uf20-0637.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0637.cnf")
}
//

///|
test "uf20-0156.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0156.cnf")
}
//

///|
test "uf20-0997.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0997.cnf")
}
//

///|
test "uf20-0422.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0422.cnf")
}
//

///|
test "uf20-0296.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0296.cnf")
}
//

///|
test "uf20-0811.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0811.cnf")
}
//

///|
test "uf20-0776.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0776.cnf")
}
//

///|
test "uf20-0660.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0660.cnf")
}
//

///|
test "uf20-0334.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0334.cnf")
}
//

///|
test "uf20-0420.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0420.cnf")
}
//

///|
test "uf20-0220.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0220.cnf")
}
//

///|
test "uf20-0348.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0348.cnf")
}
//

///|
test "uf20-0893.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0893.cnf")
}
//

///|
test "uf20-0455.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0455.cnf")
}
//

///|
test "uf20-012.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-012.cnf")
}
//

///|
test "uf20-092.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-092.cnf")
}
//

///|
test "uf20-0990.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0990.cnf")
}
//

///|
test "uf20-0337.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0337.cnf")
}

///|
test "uf20-0985.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0985.cnf")
}

///|
test "uf20-0778.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0778.cnf")
}

///|
test "uf20-0626.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0626.cnf")
}

///|
test "uf20-0344.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0344.cnf")
}

///|
test "uf20-0443.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0443.cnf")
}

///|
test "uf20-0339.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0339.cnf")
}
//

///|
test "uf20-0541.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0541.cnf")
}
//

///|
test "uf20-0931.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0931.cnf")
}
//

///|
test "uf20-0274.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0274.cnf")
}
//

///|
test "uf20-0373.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0373.cnf")
}
//

///|
test "uf20-0980.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0980.cnf")
}
//

///|
test "uf20-0370.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0370.cnf")
}
//

///|
test "uf20-0755.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0755.cnf")
}
//

///|
test "uf20-0316.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0316.cnf")
}
//

///|
test "uf20-0213.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0213.cnf")
}
//

///|
test "uf20-0126.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0126.cnf")
}
//

///|
test "uf20-0313.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0313.cnf")
}

///|
test "uf20-0938.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0938.cnf")
}

///|
test "uf20-0678.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0678.cnf")
}
//

///|
test "uf20-0308.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0308.cnf")
}
//

///|
test "uf20-0434.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0434.cnf")
}
//

///|
test "uf20-0262.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0262.cnf")
}
//

///|
test "uf20-017.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-017.cnf")
}
//

///|
test "uf20-0116.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0116.cnf")
}
//

///|
test "uf20-0760.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0760.cnf")
}
//

///|
test "uf20-0846.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0846.cnf")
}
//

///|
test "uf20-0963.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0963.cnf")
}
//

///|
test "uf20-0447.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0447.cnf")
}
//

///|
test "uf20-0392.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0392.cnf")
}

///|
test "uf20-0442.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0442.cnf")
}

///|
test "uf20-0861.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0861.cnf")
}
//

///|
test "uf20-0247.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0247.cnf")
}

///|
test "uf20-0712.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0712.cnf")
}

///|
test "uf20-0825.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0825.cnf")
}

///|
test "uf20-0894.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0894.cnf")
}
//

///|
test "uf20-0667.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0667.cnf")
}
//

///|
test "uf20-0790.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0790.cnf")
}
//

///|
test "uf20-0615.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0615.cnf")
}
//

///|
test "uf20-0545.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0545.cnf")
}
//

///|
test "uf20-0727.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0727.cnf")
}
//

///|
test "uf20-0481.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0481.cnf")
}

///|
test "uf20-0403.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0403.cnf")
}

///|
test "uf20-021.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-021.cnf")
}

///|
test "uf20-0884.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0884.cnf")
}

///|
test "uf20-0623.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0623.cnf")
}

///|
test "uf20-0740.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0740.cnf")
}

///|
test "uf20-0164.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0164.cnf")
}

///|
test "uf20-0575.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0575.cnf")
}

///|
test "uf20-0270.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0270.cnf")
}

///|
test "uf20-0993.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0993.cnf")
}

///|
test "uf20-0741.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0741.cnf")
}

///|
test "uf20-0534.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0534.cnf")
}

///|
test "uf20-0837.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0837.cnf")
}

///|
test "uf20-0731.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0731.cnf")
}

///|
test "uf20-022.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-022.cnf")
}

///|
test "uf20-0510.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0510.cnf")
}

///|
test "uf20-0929.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0929.cnf")
}

///|
test "uf20-0847.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0847.cnf")
}

///|
test "uf20-0531.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0531.cnf")
}

///|
test "uf20-0901.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0901.cnf")
}

///|
test "uf20-06.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-06.cnf")
}

///|
test "uf20-0354.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0354.cnf")
}

///|
test "uf20-0976.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0976.cnf")
}

///|
test "uf20-059.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-059.cnf")
}

///|
test "uf20-0641.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0641.cnf")
}

///|
test "uf20-0124.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0124.cnf")
}

///|
test "uf20-0801.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0801.cnf")
}

///|
test "uf20-0831.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0831.cnf")
}

///|
test "uf20-0762.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0762.cnf")
}

///|
test "uf20-037.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-037.cnf")
}

///|
test "uf20-0738.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0738.cnf")
}

///|
test "uf20-0492.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0492.cnf")
}

///|
test "uf20-0393.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0393.cnf")
}

///|
test "uf20-0273.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0273.cnf")
}

///|
test "uf20-0484.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0484.cnf")
}

///|
test "uf20-0230.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0230.cnf")
}

///|
test "uf20-0956.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0956.cnf")
}

///|
test "uf20-0815.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0815.cnf")
}

///|
test "uf20-0192.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0192.cnf")
}

///|
test "uf20-0688.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0688.cnf")
}

///|
test "uf20-0599.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0599.cnf")
}

///|
test "uf20-0828.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0828.cnf")
}

///|
test "uf20-0226.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0226.cnf")
}

///|
test "uf20-0675.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0675.cnf")
}

///|
test "uf20-0628.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0628.cnf")
}

///|
test "uf20-05.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-05.cnf")
}

///|
test "uf20-0775.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0775.cnf")
}

///|
test "uf20-0981.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0981.cnf")
}

///|
test "uf20-0223.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0223.cnf")
}

///|
test "uf20-0282.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0282.cnf")
}

///|
test "uf20-0671.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0671.cnf")
}

///|
test "uf20-0709.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0709.cnf")
}

///|
test "uf20-0729.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0729.cnf")
}

///|
test "uf20-0452.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0452.cnf")
}

///|
test "uf20-0462.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0462.cnf")
}

///|
test "uf20-0983.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0983.cnf")
}

///|
test "uf20-0713.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0713.cnf")
}

///|
test "uf20-0470.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0470.cnf")
}

///|
test "uf20-0780.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0780.cnf")
}

///|
test "uf20-0591.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0591.cnf")
}

///|
test "uf20-0601.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0601.cnf")
}

///|
test "uf20-0908.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0908.cnf")
}

///|
test "uf20-0363.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0363.cnf")
}

///|
test "uf20-0360.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0360.cnf")
}

///|
test "uf20-0180.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0180.cnf")
}

///|
test "uf20-0566.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0566.cnf")
}

///|
test "uf20-063.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-063.cnf")
}

///|
test "uf20-0987.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0987.cnf")
}

///|
test "uf20-0318.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0318.cnf")
}

///|
test "uf20-0212.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0212.cnf")
}

///|
test "uf20-0133.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0133.cnf")
}

///|
test "uf20-0272.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0272.cnf")
}

///|
test "uf20-0387.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0387.cnf")
}

///|
test "uf20-0435.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0435.cnf")
}

///|
test "uf20-0966.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0966.cnf")
}

///|
test "uf20-0400.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0400.cnf")
}

///|
test "uf20-0717.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0717.cnf")
}

///|
test "uf20-045.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-045.cnf")
}

///|
test "uf20-0646.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0646.cnf")
}

///|
test "uf20-0521.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0521.cnf")
}

///|
test "uf20-0613.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0613.cnf")
}

///|
test "uf20-0668.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0668.cnf")
}

///|
test "uf20-0128.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0128.cnf")
}

///|
test "uf20-0539.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0539.cnf")
}

///|
test "uf20-0979.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0979.cnf")
}

///|
test "uf20-0683.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0683.cnf")
}

///|
test "uf20-0839.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0839.cnf")
}

///|
test "uf20-0621.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0621.cnf")
}

///|
test "uf20-0307.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0307.cnf")
}

///|
test "uf20-0785.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0785.cnf")
}

///|
test "uf20-0781.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0781.cnf")
}

///|
test "uf20-0909.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0909.cnf")
}

///|
test "uf20-0438.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0438.cnf")
}

///|
test "uf20-071.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-071.cnf")
}

///|
test "uf20-0352.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0352.cnf")
}

///|
test "uf20-0886.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0886.cnf")
}

///|
test "uf20-0793.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0793.cnf")
}

///|
test "uf20-080.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-080.cnf")
}

///|
test "uf20-0814.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0814.cnf")
}

///|
test "uf20-0813.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0813.cnf")
}

///|
test "uf20-0485.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0485.cnf")
}

///|
test "uf20-0996.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0996.cnf")
}

///|
test "uf20-0764.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0764.cnf")
}

///|
test "uf20-0798.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0798.cnf")
}

///|
test "uf20-0260.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0260.cnf")
}

///|
test "uf20-0603.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0603.cnf")
}

///|
test "uf20-0238.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0238.cnf")
}

///|
test "uf20-0877.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0877.cnf")
}

///|
test "uf20-0467.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0467.cnf")
}

///|
test "uf20-0335.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0335.cnf")
}

///|
test "uf20-0475.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0475.cnf")
}

///|
test "uf20-0104.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0104.cnf")
}

///|
test "uf20-0105.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0105.cnf")
}

///|
test "uf20-0991.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0991.cnf")
}

///|
test "uf20-0291.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0291.cnf")
}

///|
test "uf20-0205.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0205.cnf")
}

///|
test "uf20-0246.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0246.cnf")
}

///|
test "uf20-0695.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0695.cnf")
}

///|
test "uf20-0995.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0995.cnf")
}

///|
test "uf20-0295.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0295.cnf")
}

///|
test "uf20-0448.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0448.cnf")
}

///|
test "uf20-0283.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0283.cnf")
}

///|
test "uf20-0194.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0194.cnf")
}

///|
test "uf20-0221.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0221.cnf")
}

///|
test "uf20-0258.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0258.cnf")
}

///|
test "uf20-0488.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0488.cnf")
}

///|
test "uf20-0209.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0209.cnf")
}

///|
test "uf20-0112.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0112.cnf")
}

///|
test "uf20-0820.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0820.cnf")
}

///|
test "uf20-0881.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0881.cnf")
}

///|
test "uf20-0526.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0526.cnf")
}

///|
test "uf20-03.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-03.cnf")
}

///|
test "uf20-0240.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0240.cnf")
}

///|
test "uf20-0486.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0486.cnf")
}

///|
test "uf20-083.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-083.cnf")
}

///|
test "uf20-0349.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0349.cnf")
}

///|
test "uf20-035.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-035.cnf")
}

///|
test "uf20-0290.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0290.cnf")
}

///|
test "uf20-0752.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0752.cnf")
}

///|
test "uf20-0644.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0644.cnf")
}

///|
test "uf20-0535.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0535.cnf")
}

///|
test "uf20-0812.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0812.cnf")
}

///|
test "uf20-0888.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0888.cnf")
}

///|
test "uf20-0823.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0823.cnf")
}

///|
test "uf20-0614.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0614.cnf")
}

///|
test "uf20-0397.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0397.cnf")
}

///|
test "uf20-0278.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0278.cnf")
}

///|
test "uf20-0520.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0520.cnf")
}

///|
test "uf20-0659.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0659.cnf")
}

///|
test "uf20-0162.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0162.cnf")
}

///|
test "uf20-0907.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0907.cnf")
}

///|
test "uf20-0821.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0821.cnf")
}

///|
test "uf20-0612.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0612.cnf")
}

///|
test "uf20-0992.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0992.cnf")
}

///|
test "uf20-0122.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0122.cnf")
}

///|
test "uf20-0454.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0454.cnf")
}

///|
test "uf20-0367.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0367.cnf")
}

///|
test "uf20-0721.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0721.cnf")
}

///|
test "uf20-0988.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0988.cnf")
}

///|
test "uf20-0719.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0719.cnf")
}

///|
test "uf20-0404.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0404.cnf")
}

///|
test "uf20-0129.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0129.cnf")
}

///|
test "uf20-0233.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0233.cnf")
}

///|
test "uf20-0527.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0527.cnf")
}

///|
test "uf20-0809.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0809.cnf")
}

///|
test "uf20-0582.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0582.cnf")
}

///|
test "uf20-0948.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0948.cnf")
}

///|
test "uf20-0689.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0689.cnf")
}

///|
test "uf20-0742.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0742.cnf")
}

///|
test "uf20-0632.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0632.cnf")
}

///|
test "uf20-0449.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0449.cnf")
}

///|
test "uf20-0602.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0602.cnf")
}

///|
test "uf20-0351.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0351.cnf")
}

///|
test "uf20-0311.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0311.cnf")
}

///|
test "uf20-0761.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0761.cnf")
}

///|
test "uf20-0648.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0648.cnf")
}

///|
test "uf20-0952.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0952.cnf")
}

///|
test "uf20-0944.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0944.cnf")
}

///|
test "uf20-0277.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0277.cnf")
}

///|
test "uf20-0107.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0107.cnf")
}

///|
test "uf20-0158.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0158.cnf")
}

///|
test "uf20-0331.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0331.cnf")
}

///|
test "uf20-0905.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0905.cnf")
}

///|
test "uf20-0961.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0961.cnf")
}

///|
test "uf20-0101.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0101.cnf")
}

///|
test "uf20-010.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-010.cnf")
}

///|
test "uf20-0570.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0570.cnf")
}

///|
test "uf20-0969.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0969.cnf")
}

///|
test "uf20-0690.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0690.cnf")
}

///|
test "uf20-0456.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0456.cnf")
}

///|
test "uf20-0977.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0977.cnf")
}

///|
test "uf20-077.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-077.cnf")
}

///|
test "uf20-0687.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0687.cnf")
}

///|
test "uf20-0281.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0281.cnf")
}

///|
test "uf20-0895.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0895.cnf")
}

///|
test "uf20-0810.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0810.cnf")
}

///|
test "uf20-0664.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0664.cnf")
}

///|
test "uf20-0377.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0377.cnf")
}

///|
test "uf20-0546.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0546.cnf")
}

///|
test "uf20-0699.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0699.cnf")
}

///|
test "uf20-049.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-049.cnf")
}

///|
test "uf20-0110.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0110.cnf")
}

///|
test "uf20-016.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-016.cnf")
}

///|
test "uf20-0243.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0243.cnf")
}

///|
test "uf20-0576.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0576.cnf")
}

///|
test "uf20-067.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-067.cnf")
}

///|
test "uf20-0848.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0848.cnf")
}

///|
test "uf20-0544.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0544.cnf")
}

///|
test "uf20-0471.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0471.cnf")
}

///|
test "uf20-0746.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0746.cnf")
}

///|
test "uf20-0562.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0562.cnf")
}

///|
test "uf20-0309.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0309.cnf")
}

///|
test "uf20-0432.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0432.cnf")
}

///|
test "uf20-0109.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0109.cnf")
}

///|
test "uf20-0127.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0127.cnf")
}

///|
test "uf20-0558.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0558.cnf")
}

///|
test "uf20-0106.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0106.cnf")
}

///|
test "uf20-0293.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0293.cnf")
}

///|
test "uf20-0913.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0913.cnf")
}

///|
test "uf20-020.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-020.cnf")
}

///|
test "uf20-0341.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0341.cnf")
}

///|
test "uf20-0670.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0670.cnf")
}

///|
test "uf20-0661.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0661.cnf")
}

///|
test "uf20-082.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-082.cnf")
}

///|
test "uf20-0300.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0300.cnf")
}

///|
test "uf20-0353.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0353.cnf")
}

///|
test "uf20-0183.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0183.cnf")
}

///|
test "uf20-0427.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0427.cnf")
}

///|
test "uf20-0803.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0803.cnf")
}

///|
test "uf20-0100.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0100.cnf")
}

///|
test "uf20-0245.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0245.cnf")
}

///|
test "uf20-0113.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0113.cnf")
}

///|
test "uf20-0201.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0201.cnf")
}

///|
test "uf20-0559.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0559.cnf")
}

///|
test "uf20-0185.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0185.cnf")
}

///|
test "uf20-0975.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0975.cnf")
}

///|
test "uf20-0175.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0175.cnf")
}

///|
test "uf20-0871.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0871.cnf")
}

///|
test "uf20-088.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-088.cnf")
}

///|
test "uf20-0747.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0747.cnf")
}

///|
test "uf20-0193.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0193.cnf")
}

///|
test "uf20-0301.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0301.cnf")
}

///|
test "uf20-0577.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0577.cnf")
}

///|
test "uf20-0214.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0214.cnf")
}

///|
test "uf20-02.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-02.cnf")
}

///|
test "uf20-0477.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0477.cnf")
}

///|
test "uf20-0630.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0630.cnf")
}

///|
test "uf20-0302.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0302.cnf")
}

///|
test "uf20-0461.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0461.cnf")
}

///|
test "uf20-0885.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0885.cnf")
}

///|
test "uf20-0410.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0410.cnf")
}

///|
test "uf20-0751.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0751.cnf")
}

///|
test "uf20-0184.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0184.cnf")
}

///|
test "uf20-026.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-026.cnf")
}

///|
test "uf20-0342.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0342.cnf")
}

///|
test "uf20-0703.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0703.cnf")
}

///|
test "uf20-0859.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0859.cnf")
}

///|
test "uf20-0503.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0503.cnf")
}

///|
test "uf20-0618.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0618.cnf")
}

///|
test "uf20-0444.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0444.cnf")
}

///|
test "uf20-0178.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0178.cnf")
}

///|
test "uf20-0855.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0855.cnf")
}

///|
test "uf20-0658.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0658.cnf")
}

///|
test "uf20-0653.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0653.cnf")
}

///|
test "uf20-0827.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0827.cnf")
}

///|
test "uf20-0306.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0306.cnf")
}

///|
test "uf20-0537.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0537.cnf")
}

///|
test "uf20-0436.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0436.cnf")
}

///|
test "uf20-086.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-086.cnf")
}

///|
test "uf20-0947.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0947.cnf")
}

///|
test "uf20-0608.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0608.cnf")
}

///|
test "uf20-0770.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0770.cnf")
}

///|
test "uf20-062.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-062.cnf")
}

///|
test "uf20-094.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-094.cnf")
}

///|
test "uf20-031.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-031.cnf")
}

///|
test "uf20-0132.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0132.cnf")
}

///|
test "uf20-0584.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0584.cnf")
}

///|
test "uf20-0824.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0824.cnf")
}

///|
test "uf20-0171.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0171.cnf")
}

///|
test "uf20-0718.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0718.cnf")
}

///|
test "uf20-060.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-060.cnf")
}

///|
test "uf20-0936.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0936.cnf")
}

///|
test "uf20-0134.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0134.cnf")
}

///|
test "uf20-0343.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0343.cnf")
}

///|
test "uf20-0241.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0241.cnf")
}

///|
test "uf20-0536.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0536.cnf")
}

///|
test "uf20-0791.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0791.cnf")
}

///|
test "uf20-068.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-068.cnf")
}

///|
test "uf20-0597.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0597.cnf")
}

///|
test "uf20-0375.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0375.cnf")
}

///|
test "uf20-061.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-061.cnf")
}

///|
test "uf20-0429.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0429.cnf")
}

///|
test "uf20-0669.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0669.cnf")
}

///|
test "uf20-065.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-065.cnf")
}

///|
test "uf20-0590.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0590.cnf")
}

///|
test "uf20-0204.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0204.cnf")
}

///|
test "uf20-0264.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0264.cnf")
}

///|
test "uf20-066.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-066.cnf")
}

///|
test "uf20-0870.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0870.cnf")
}

///|
test "uf20-019.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-019.cnf")
}

///|
test "uf20-0928.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0928.cnf")
}

///|
test "uf20-034.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-034.cnf")
}

///|
test "uf20-0379.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0379.cnf")
}

///|
test "uf20-0195.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0195.cnf")
}

///|
test "uf20-047.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-047.cnf")
}

///|
test "uf20-0730.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0730.cnf")
}

///|
test "uf20-041.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-041.cnf")
}

///|
test "uf20-0777.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0777.cnf")
}

///|
test "uf20-0550.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0550.cnf")
}

///|
test "uf20-0693.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0693.cnf")
}

///|
test "uf20-0794.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0794.cnf")
}

///|
test "uf20-0692.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0692.cnf")
}

///|
test "uf20-0206.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0206.cnf")
}

///|
test "uf20-0819.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0819.cnf")
}

///|
test "uf20-0663.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0663.cnf")
}

///|
test "uf20-0483.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0483.cnf")
}

///|
test "uf20-0512.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0512.cnf")
}

///|
test "uf20-0563.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0563.cnf")
}

///|
test "uf20-0119.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0119.cnf")
}

///|
test "uf20-0554.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0554.cnf")
}

///|
test "uf20-0700.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0700.cnf")
}

///|
test "uf20-0701.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0701.cnf")
}

///|
test "uf20-0657.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0657.cnf")
}

///|
test "uf20-0389.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0389.cnf")
}

///|
test "uf20-0437.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0437.cnf")
}

///|
test "uf20-0673.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0673.cnf")
}

///|
test "uf20-0155.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0155.cnf")
}

///|
test "uf20-0662.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0662.cnf")
}

///|
test "uf20-0368.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0368.cnf")
}

///|
test "uf20-0111.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0111.cnf")
}

///|
test "uf20-0433.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0433.cnf")
}

///|
test "uf20-0186.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0186.cnf")
}

///|
test "uf20-0850.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0850.cnf")
}

///|
test "uf20-0197.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0197.cnf")
}

///|
test "uf20-0425.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0425.cnf")
}

///|
test "uf20-0540.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0540.cnf")
}

///|
test "uf20-0191.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0191.cnf")
}

///|
test "uf20-024.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-024.cnf")
}

///|
test "uf20-0753.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0753.cnf")
}

///|
test "uf20-0942.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0942.cnf")
}

///|
test "uf20-0491.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0491.cnf")
}

///|
test "uf20-0922.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0922.cnf")
}

///|
test "uf20-0504.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0504.cnf")
}

///|
test "uf20-0457.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0457.cnf")
}

///|
test "uf20-0231.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0231.cnf")
}

///|
test "uf20-0655.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0655.cnf")
}

///|
test "uf20-0860.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0860.cnf")
}

///|
test "uf20-0620.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0620.cnf")
}

///|
test "uf20-0845.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0845.cnf")
}

///|
test "uf20-0557.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0557.cnf")
}

///|
test "uf20-0509.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0509.cnf")
}

///|
test "uf20-0378.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0378.cnf")
}

///|
test "uf20-0161.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0161.cnf")
}

///|
test "uf20-0867.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0867.cnf")
}

///|
test "uf20-0684.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0684.cnf")
}

///|
test "uf20-0724.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0724.cnf")
}

///|
test "uf20-0916.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0916.cnf")
}

///|
test "uf20-0200.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0200.cnf")
}

///|
test "uf20-0217.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0217.cnf")
}

///|
test "uf20-0478.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0478.cnf")
}

///|
test "uf20-0796.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0796.cnf")
}

///|
test "uf20-0189.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0189.cnf")
}

///|
test "uf20-0117.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0117.cnf")
}

///|
test "uf20-0259.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0259.cnf")
}

///|
test "uf20-0406.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0406.cnf")
}

///|
test "uf20-0786.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0786.cnf")
}

///|
test "uf20-078.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-078.cnf")
}

///|
test "uf20-0292.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0292.cnf")
}

///|
test "uf20-0900.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0900.cnf")
}

///|
test "uf20-048.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-048.cnf")
}

///|
test "uf20-0625.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0625.cnf")
}

///|
test "uf20-0314.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0314.cnf")
}

///|
test "uf20-0190.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0190.cnf")
}

///|
test "uf20-0891.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0891.cnf")
}

///|
test "uf20-0402.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0402.cnf")
}

///|
test "uf20-0148.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0148.cnf")
}

///|
test "uf20-0453.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0453.cnf")
}

///|
test "uf20-081.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-081.cnf")
}

///|
test "uf20-0329.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0329.cnf")
}

///|
test "uf20-0647.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0647.cnf")
}

///|
test "uf20-0409.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0409.cnf")
}

///|
test "uf20-0380.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0380.cnf")
}

///|
test "uf20-0210.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0210.cnf")
}

///|
test "uf20-0507.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0507.cnf")
}

///|
test "uf20-0142.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0142.cnf")
}

///|
test "uf20-0714.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0714.cnf")
}

///|
test "uf20-0547.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0547.cnf")
}

///|
test "uf20-0350.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0350.cnf")
}

///|
test "uf20-0682.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0682.cnf")
}

///|
test "uf20-08.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-08.cnf")
}

///|
test "uf20-0121.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0121.cnf")
}

///|
test "uf20-0508.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0508.cnf")
}

///|
test "uf20-0237.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0237.cnf")
}

///|
test "uf20-0927.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0927.cnf")
}

///|
test "uf20-0391.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0391.cnf")
}

///|
test "uf20-0523.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0523.cnf")
}

///|
test "uf20-0182.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0182.cnf")
}

///|
test "uf20-0276.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0276.cnf")
}

///|
test "uf20-0890.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0890.cnf")
}

///|
test "uf20-0459.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0459.cnf")
}

///|
test "uf20-0843.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0843.cnf")
}

///|
test "uf20-0784.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0784.cnf")
}

///|
test "uf20-01000.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-01000.cnf")
}

///|
test "uf20-0445.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0445.cnf")
}

///|
test "uf20-0446.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0446.cnf")
}

///|
test "uf20-0251.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0251.cnf")
}

///|
test "uf20-0224.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0224.cnf")
}

///|
test "uf20-0517.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0517.cnf")
}

///|
test "uf20-0347.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0347.cnf")
}

///|
test "uf20-0940.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0940.cnf")
}

///|
test "uf20-064.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-064.cnf")
}

///|
test "uf20-0279.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0279.cnf")
}

///|
test "uf20-0954.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0954.cnf")
}

///|
test "uf20-0698.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0698.cnf")
}

///|
test "uf20-0868.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0868.cnf")
}

///|
test "uf20-0372.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0372.cnf")
}

///|
test "uf20-0464.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0464.cnf")
}

///|
test "uf20-0516.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0516.cnf")
}

///|
test "uf20-0362.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0362.cnf")
}

///|
test "uf20-0799.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0799.cnf")
}

///|
test "uf20-0685.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0685.cnf")
}

///|
test "uf20-0642.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0642.cnf")
}

///|
test "uf20-0275.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0275.cnf")
}

///|
test "uf20-0745.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0745.cnf")
}

///|
test "uf20-0627.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0627.cnf")
}

///|
test "uf20-097.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-097.cnf")
}

///|
test "uf20-0596.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0596.cnf")
}

///|
test "uf20-0502.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0502.cnf")
}

///|
test "uf20-0305.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0305.cnf")
}

///|
test "uf20-0159.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0159.cnf")
}

///|
test "uf20-051.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-051.cnf")
}

///|
test "uf20-098.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-098.cnf")
}

///|
test "uf20-0636.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0636.cnf")
}

///|
test "uf20-0261.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0261.cnf")
}

///|
test "uf20-0795.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0795.cnf")
}

///|
test "uf20-0925.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0925.cnf")
}

///|
test "uf20-0358.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0358.cnf")
}

///|
test "uf20-0600.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0600.cnf")
}

///|
test "uf20-0650.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0650.cnf")
}

///|
test "uf20-0376.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0376.cnf")
}

///|
test "uf20-0356.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0356.cnf")
}

///|
test "uf20-0766.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0766.cnf")
}

///|
test "uf20-0234.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0234.cnf")
}

///|
test "uf20-0364.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0364.cnf")
}

///|
test "uf20-0616.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0616.cnf")
}

///|
test "uf20-0381.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0381.cnf")
}

///|
test "uf20-0906.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0906.cnf")
}

///|
test "uf20-0236.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0236.cnf")
}

///|
test "uf20-0304.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0304.cnf")
}

///|
test "uf20-0573.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0573.cnf")
}

///|
test "uf20-014.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-014.cnf")
}

///|
test "uf20-0598.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0598.cnf")
}

///|
test "uf20-0482.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0482.cnf")
}

///|
test "uf20-0533.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0533.cnf")
}

///|
test "uf20-0167.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0167.cnf")
}

///|
test "uf20-0733.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0733.cnf")
}

///|
test "uf20-0844.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0844.cnf")
}

///|
test "uf20-0919.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0919.cnf")
}

///|
test "uf20-0299.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0299.cnf")
}

///|
test "uf20-0355.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0355.cnf")
}

///|
test "uf20-0806.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0806.cnf")
}

///|
test "uf20-0285.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0285.cnf")
}

///|
test "uf20-0984.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0984.cnf")
}

///|
test "uf20-0696.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0696.cnf")
}

///|
test "uf20-085.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-085.cnf")
}

///|
test "uf20-0423.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0423.cnf")
}

///|
test "uf20-0266.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0266.cnf")
}

///|
test "uf20-0592.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0592.cnf")
}

///|
test "uf20-0174.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0174.cnf")
}

///|
test "uf20-0408.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0408.cnf")
}

///|
test "uf20-0617.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0617.cnf")
}

///|
test "uf20-0366.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0366.cnf")
}

///|
test "uf20-0832.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0832.cnf")
}

///|
test "uf20-0567.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0567.cnf")
}

///|
test "uf20-0838.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0838.cnf")
}

///|
test "uf20-018.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-018.cnf")
}

///|
test "uf20-074.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-074.cnf")
}

///|
test "uf20-0863.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0863.cnf")
}

///|
test "uf20-040.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-040.cnf")
}

///|
test "uf20-0834.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0834.cnf")
}

///|
test "uf20-0982.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0982.cnf")
}

///|
test "uf20-033.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-033.cnf")
}

///|
test "uf20-0585.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0585.cnf")
}

///|
test "uf20-0808.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0808.cnf")
}

///|
test "uf20-0250.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0250.cnf")
}

///|
test "uf20-0920.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0920.cnf")
}

///|
test "uf20-0783.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0783.cnf")
}

///|
test "uf20-093.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-093.cnf")
}

///|
test "uf20-0225.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0225.cnf")
}

///|
test "uf20-0958.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0958.cnf")
}

///|
test "uf20-0542.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0542.cnf")
}

///|
test "uf20-0897.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0897.cnf")
}

///|
test "uf20-0792.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0792.cnf")
}

///|
test "uf20-0763.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0763.cnf")
}

///|
test "uf20-015.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-015.cnf")
}

///|
test "uf20-0560.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0560.cnf")
}

///|
test "uf20-0549.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0549.cnf")
}

///|
test "uf20-0327.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0327.cnf")
}

///|
test "uf20-0748.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0748.cnf")
}

///|
test "uf20-0633.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0633.cnf")
}

///|
test "uf20-0862.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0862.cnf")
}

///|
test "uf20-0498.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0498.cnf")
}

///|
test "uf20-0933.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0933.cnf")
}

///|
test "uf20-0873.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0873.cnf")
}

///|
test "uf20-055.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-055.cnf")
}

///|
test "uf20-0830.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0830.cnf")
}

///|
test "uf20-0571.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0571.cnf")
}

///|
test "uf20-0840.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0840.cnf")
}

///|
test "uf20-0289.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0289.cnf")
}

///|
test "uf20-0176.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0176.cnf")
}

///|
test "uf20-0972.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0972.cnf")
}

///|
test "uf20-0137.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0137.cnf")
}

///|
test "uf20-0312.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0312.cnf")
}

///|
test "uf20-076.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-076.cnf")
}

///|
test "uf20-0413.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0413.cnf")
}

///|
test "uf20-0424.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0424.cnf")
}

///|
test "uf20-0767.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0767.cnf")
}

///|
test "uf20-0774.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0774.cnf")
}

///|
test "uf20-0396.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0396.cnf")
}

///|
test "uf20-0469.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0469.cnf")
}

///|
test "uf20-0336.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0336.cnf")
}

///|
test "uf20-0665.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0665.cnf")
}

///|
test "uf20-0583.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0583.cnf")
}

///|
test "uf20-0939.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0939.cnf")
}

///|
test "uf20-0479.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0479.cnf")
}

///|
test "uf20-0912.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0912.cnf")
}

///|
test "uf20-0773.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0773.cnf")
}

///|
test "uf20-030.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-030.cnf")
}

///|
test "uf20-0465.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0465.cnf")
}

///|
test "uf20-0411.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0411.cnf")
}

///|
test "uf20-0826.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0826.cnf")
}

///|
test "uf20-0271.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0271.cnf")
}

///|
test "uf20-0118.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0118.cnf")
}

///|
test "uf20-0674.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0674.cnf")
}

///|
test "uf20-0704.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0704.cnf")
}

///|
test "uf20-0728.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0728.cnf")
}

///|
test "uf20-0622.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0622.cnf")
}

///|
test "uf20-0211.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0211.cnf")
}

///|
test "uf20-0551.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0551.cnf")
}

///|
test "uf20-0875.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0875.cnf")
}

///|
test "uf20-0989.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0989.cnf")
}

///|
test "uf20-0883.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0883.cnf")
}

///|
test "uf20-0734.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0734.cnf")
}

///|
test "uf20-0681.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0681.cnf")
}

///|
test "uf20-0286.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0286.cnf")
}

///|
test "uf20-0248.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0248.cnf")
}

///|
test "uf20-0787.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0787.cnf")
}

///|
test "uf20-0640.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0640.cnf")
}

///|
test "uf20-0518.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0518.cnf")
}

///|
test "uf20-0735.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0735.cnf")
}

///|
test "uf20-0579.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0579.cnf")
}

///|
test "uf20-0921.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0921.cnf")
}

///|
test "uf20-0346.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0346.cnf")
}

///|
test "uf20-0910.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0910.cnf")
}

///|
test "uf20-0949.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0949.cnf")
}

///|
test "uf20-0769.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0769.cnf")
}

///|
test "uf20-0725.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0725.cnf")
}

///|
test "uf20-0866.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0866.cnf")
}

///|
test "uf20-0756.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0756.cnf")
}

///|
test "uf20-0252.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0252.cnf")
}

///|
test "uf20-0605.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0605.cnf")
}

///|
test "uf20-0514.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0514.cnf")
}

///|
test "uf20-013.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-013.cnf")
}

///|
test "uf20-0319.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0319.cnf")
}

///|
test "uf20-057.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-057.cnf")
}

///|
test "uf20-0493.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0493.cnf")
}

///|
test "uf20-0759.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0759.cnf")
}

///|
test "uf20-0589.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0589.cnf")
}

///|
test "uf20-0320.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0320.cnf")
}

///|
test "uf20-0971.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0971.cnf")
}

///|
test "uf20-0951.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0951.cnf")
}

///|
test "uf20-0807.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0807.cnf")
}

///|
test "uf20-0772.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0772.cnf")
}

///|
test "uf20-0294.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0294.cnf")
}

///|
test "uf20-0974.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0974.cnf")
}

///|
test "uf20-0750.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0750.cnf")
}

///|
test "uf20-0505.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0505.cnf")
}

///|
test "uf20-0421.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0421.cnf")
}

///|
test "uf20-0511.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0511.cnf")
}

///|
test "uf20-0317.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0317.cnf")
}

///|
test "uf20-0244.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0244.cnf")
}

///|
test "uf20-0384.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0384.cnf")
}

///|
test "uf20-0970.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0970.cnf")
}

///|
test "uf20-0460.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0460.cnf")
}

///|
test "uf20-0412.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0412.cnf")
}

///|
test "uf20-0418.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0418.cnf")
}

///|
test "uf20-0986.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0986.cnf")
}

///|
test "uf20-0904.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0904.cnf")
}

///|
test "uf20-0371.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0371.cnf")
}

///|
test "uf20-0263.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0263.cnf")
}

///|
test "uf20-0805.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0805.cnf")
}

///|
test "uf20-0874.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0874.cnf")
}

///|
test "uf20-0188.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0188.cnf")
}

///|
test "uf20-0950.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0950.cnf")
}

///|
test "uf20-087.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-087.cnf")
}

///|
test "uf20-0474.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0474.cnf")
}

///|
test "uf20-0287.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0287.cnf")
}

///|
test "uf20-0463.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0463.cnf")
}

///|
test "uf20-0131.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0131.cnf")
}

///|
test "uf20-0430.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0430.cnf")
}

///|
test "uf20-0835.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0835.cnf")
}

///|
test "uf20-0946.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0946.cnf")
}

///|
test "uf20-046.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-046.cnf")
}

///|
test "uf20-0666.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0666.cnf")
}

///|
test "uf20-0943.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0943.cnf")
}

///|
test "uf20-0857.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0857.cnf")
}

///|
test "uf20-0606.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0606.cnf")
}

///|
test "uf20-0968.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0968.cnf")
}

///|
test "uf20-0476.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0476.cnf")
}

///|
test "uf20-0528.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0528.cnf")
}

///|
test "uf20-0955.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0955.cnf")
}

///|
test "uf20-0882.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0882.cnf")
}

///|
test "uf20-0707.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0707.cnf")
}

///|
test "uf20-0357.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0357.cnf")
}

///|
test "uf20-0686.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0686.cnf")
}

///|
test "uf20-0953.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0953.cnf")
}

///|
test "uf20-0147.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0147.cnf")
}

///|
test "uf20-0323.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0323.cnf")
}

///|
test "uf20-0538.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0538.cnf")
}

///|
test "uf20-0441.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0441.cnf")
}

///|
test "uf20-0649.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0649.cnf")
}

///|
test "uf20-023.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-023.cnf")
}

///|
test "uf20-038.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-038.cnf")
}

///|
test "uf20-0765.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0765.cnf")
}

///|
test "uf20-0858.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0858.cnf")
}

///|
test "uf20-0166.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0166.cnf")
}

///|
test "uf20-036.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-036.cnf")
}

///|
test "uf20-0934.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0934.cnf")
}

///|
test "uf20-0588.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0588.cnf")
}

///|
test "uf20-0782.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0782.cnf")
}

///|
test "uf20-0145.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0145.cnf")
}

///|
test "uf20-0219.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0219.cnf")
}

///|
test "uf20-052.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-052.cnf")
}

///|
test "uf20-0431.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0431.cnf")
}

///|
test "uf20-0440.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0440.cnf")
}

///|
test "uf20-0923.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0923.cnf")
}

///|
test "uf20-0841.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0841.cnf")
}

///|
test "uf20-0160.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0160.cnf")
}

///|
test "uf20-0960.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0960.cnf")
}

///|
test "uf20-0607.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0607.cnf")
}

///|
test "uf20-0672.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0672.cnf")
}

///|
test "uf20-0594.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0594.cnf")
}

///|
test "uf20-069.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-069.cnf")
}

///|
test "uf20-044.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-044.cnf")
}

///|
test "uf20-0280.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0280.cnf")
}

///|
test "uf20-0789.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0789.cnf")
}

///|
test "uf20-056.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-056.cnf")
}

///|
test "uf20-0473.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0473.cnf")
}

///|
test "uf20-043.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-043.cnf")
}

///|
test "uf20-0578.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0578.cnf")
}

///|
test "uf20-0593.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0593.cnf")
}

///|
test "uf20-09.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-09.cnf")
}

///|
test "uf20-0723.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0723.cnf")
}

///|
test "uf20-0239.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0239.cnf")
}

///|
test "uf20-0333.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0333.cnf")
}

///|
test "uf20-0926.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0926.cnf")
}

///|
test "uf20-0149.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0149.cnf")
}

///|
test "uf20-0298.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0298.cnf")
}

///|
test "uf20-0651.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0651.cnf")
}

///|
test "uf20-0501.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0501.cnf")
}

///|
test "uf20-0361.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0361.cnf")
}

///|
test "uf20-0506.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0506.cnf")
}

///|
test "uf20-0321.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0321.cnf")
}

///|
test "uf20-0256.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0256.cnf")
}

///|
test "uf20-0879.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0879.cnf")
}

///|
test "uf20-0439.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0439.cnf")
}

///|
test "uf20-0215.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0215.cnf")
}

///|
test "uf20-0887.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0887.cnf")
}

///|
test "uf20-0818.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0818.cnf")
}

///|
test "uf20-0207.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0207.cnf")
}

///|
test "uf20-0604.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0604.cnf")
}

///|
test "uf20-0385.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0385.cnf")
}

///|
test "uf20-0340.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0340.cnf")
}

///|
test "uf20-0419.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0419.cnf")
}

///|
test "uf20-0324.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0324.cnf")
}

///|
test "uf20-0800.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0800.cnf")
}

///|
test "uf20-0426.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0426.cnf")
}

///|
test "uf20-0744.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0744.cnf")
}

///|
test "uf20-0586.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0586.cnf")
}

///|
test "uf20-0915.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0915.cnf")
}

///|
test "uf20-0532.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0532.cnf")
}

///|
test "uf20-0522.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0522.cnf")
}

///|
test "uf20-0911.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0911.cnf")
}

///|
test "uf20-0268.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0268.cnf")
}

///|
test "uf20-0255.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0255.cnf")
}

///|
test "uf20-0395.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0395.cnf")
}

///|
test "uf20-0269.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0269.cnf")
}

///|
test "uf20-0973.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0973.cnf")
}

///|
test "uf20-0108.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0108.cnf")
}

///|
test "uf20-0836.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0836.cnf")
}

///|
test "uf20-0165.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0165.cnf")
}

///|
test "uf20-0930.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0930.cnf")
}

///|
test "uf20-0235.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0235.cnf")
}

///|
test "uf20-0499.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0499.cnf")
}

///|
test "uf20-091.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-091.cnf")
}

///|
test "uf20-0326.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0326.cnf")
}

///|
test "uf20-0144.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0144.cnf")
}

///|
test "uf20-0856.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0856.cnf")
}

///|
test "uf20-0853.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0853.cnf")
}

///|
test "uf20-0315.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0315.cnf")
}

///|
test "uf20-0878.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0878.cnf")
}

///|
test "uf20-0345.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0345.cnf")
}

///|
test "uf20-0876.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0876.cnf")
}

///|
test "uf20-0609.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0609.cnf")
}

///|
test "uf20-0722.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0722.cnf")
}

///|
test "uf20-0999.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0999.cnf")
}

///|
test "uf20-0227.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0227.cnf")
}

///|
test "uf20-0749.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0749.cnf")
}

///|
test "uf20-0556.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0556.cnf")
}

///|
test "uf20-0138.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0138.cnf")
}

///|
test "uf20-0638.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0638.cnf")
}

///|
test "uf20-0143.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0143.cnf")
}

///|
test "uf20-0822.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0822.cnf")
}

///|
test "uf20-0580.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0580.cnf")
}

///|
test "uf20-0631.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0631.cnf")
}

///|
test "uf20-0500.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0500.cnf")
}

///|
test "uf20-0330.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0330.cnf")
}

///|
test "uf20-0369.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0369.cnf")
}

///|
test "uf20-0359.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0359.cnf")
}

///|
test "uf20-011.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-011.cnf")
}

///|
test "uf20-0896.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0896.cnf")
}

///|
test "uf20-0998.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0998.cnf")
}

///|
test "uf20-07.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-07.cnf")
}

///|
test "uf20-070.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-070.cnf")
}

///|
test "uf20-0365.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0365.cnf")
}

///|
test "uf20-0388.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0388.cnf")
}

///|
test "uf20-0865.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0865.cnf")
}

///|
test "uf20-0639.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0639.cnf")
}

///|
test "uf20-0151.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0151.cnf")
}

///|
test "uf20-0218.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0218.cnf")
}

///|
test "uf20-0842.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0842.cnf")
}

///|
test "uf20-0383.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0383.cnf")
}

///|
test "uf20-0924.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0924.cnf")
}

///|
test "uf20-0451.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0451.cnf")
}

///|
test "uf20-0130.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0130.cnf")
}

///|
test "uf20-0694.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0694.cnf")
}

///|
test "uf20-0565.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0565.cnf")
}

///|
test "uf20-0152.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0152.cnf")
}

///|
test "uf20-0715.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0715.cnf")
}

///|
test "uf20-0228.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0228.cnf")
}

///|
test "uf20-0864.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0864.cnf")
}

///|
test "uf20-0572.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0572.cnf")
}

///|
test "uf20-0705.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0705.cnf")
}

///|
test "uf20-0635.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0635.cnf")
}

///|
test "uf20-0797.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0797.cnf")
}

///|
test "uf20-0941.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0941.cnf")
}

///|
test "uf20-0564.cnf" {
  check_sat("./dimacs/uf20v91c/uf20-0564.cnf")
}
