///|
test "uf50-0923.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0923.cnf")
}

///|
test "uf50-0814.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0814.cnf")
}

///|
test "uf50-0435.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0435.cnf")
}

///|
test "uf50-0851.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0851.cnf")
}

///|
test "uf50-0233.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0233.cnf")
}

///|
test "uf50-0359.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0359.cnf")
}

///|
test "uf50-0622.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0622.cnf")
}

///|
test "uf50-0993.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0993.cnf")
}

///|
test "uf50-0774.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0774.cnf")
}

///|
test "uf50-0991.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0991.cnf")
}

///|
test "uf50-0445.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0445.cnf")
}

///|
test "uf50-0973.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0973.cnf")
}

///|
test "uf50-0842.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0842.cnf")
}

///|
test "uf50-0916.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0916.cnf")
}

///|
test "uf50-0699.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0699.cnf")
}

///|
test "uf50-0671.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0671.cnf")
}

///|
test "uf50-0685.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0685.cnf")
}

///|
test "uf50-026.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-026.cnf")
}

///|
test "uf50-0199.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0199.cnf")
}

///|
test "uf50-0311.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0311.cnf")
}

///|
test "uf50-0449.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0449.cnf")
}

///|
test "uf50-0348.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0348.cnf")
}

///|
test "uf50-0399.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0399.cnf")
}

///|
test "uf50-0603.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0603.cnf")
}

///|
test "uf50-0988.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0988.cnf")
}

///|
test "uf50-0573.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0573.cnf")
}

///|
test "uf50-0897.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0897.cnf")
}

///|
test "uf50-0617.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0617.cnf")
}

///|
test "uf50-0907.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0907.cnf")
}

///|
test "uf50-0734.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0734.cnf")
}

///|
test "uf50-0236.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0236.cnf")
}

///|
test "uf50-0611.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0611.cnf")
}

///|
test "uf50-0483.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0483.cnf")
}

///|
test "uf50-0663.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0663.cnf")
}

///|
test "uf50-0375.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0375.cnf")
}

///|
test "uf50-0785.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0785.cnf")
}

///|
test "uf50-0306.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0306.cnf")
}

///|
test "uf50-0208.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0208.cnf")
}

///|
test "uf50-0464.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0464.cnf")
}

///|
test "uf50-0803.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0803.cnf")
}

///|
test "uf50-0829.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0829.cnf")
}

///|
test "uf50-0353.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0353.cnf")
}

///|
test "uf50-0273.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0273.cnf")
}

///|
test "uf50-0357.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0357.cnf")
}

///|
test "uf50-0212.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0212.cnf")
}

///|
test "uf50-0807.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0807.cnf")
}

///|
test "uf50-0501.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0501.cnf")
}

///|
test "uf50-0680.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0680.cnf")
}

///|
test "uf50-079.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-079.cnf")
}

///|
test "uf50-0459.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0459.cnf")
}

///|
test "uf50-086.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-086.cnf")
}

///|
test "uf50-0826.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0826.cnf")
}

///|
test "uf50-0545.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0545.cnf")
}

///|
test "uf50-0142.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0142.cnf")
}

///|
test "uf50-0723.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0723.cnf")
}

///|
test "uf50-0886.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0886.cnf")
}

///|
test "uf50-0384.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0384.cnf")
}

///|
test "uf50-01.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-01.cnf")
}

///|
test "uf50-0125.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0125.cnf")
}

///|
test "uf50-0778.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0778.cnf")
}

///|
test "uf50-0462.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0462.cnf")
}

///|
test "uf50-0637.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0637.cnf")
}

///|
test "uf50-0700.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0700.cnf")
}

///|
test "uf50-0313.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0313.cnf")
}

///|
test "uf50-0915.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0915.cnf")
}

///|
test "uf50-0516.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0516.cnf")
}

///|
test "uf50-0623.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0623.cnf")
}

///|
test "uf50-0857.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0857.cnf")
}

///|
test "uf50-0321.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0321.cnf")
}

///|
test "uf50-0268.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0268.cnf")
}

///|
test "uf50-0182.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0182.cnf")
}

///|
test "uf50-0517.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0517.cnf")
}

///|
test "uf50-044.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-044.cnf")
}

///|
test "uf50-0580.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0580.cnf")
}

///|
test "uf50-0369.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0369.cnf")
}

///|
test "uf50-0902.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0902.cnf")
}

///|
test "uf50-0773.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0773.cnf")
}

///|
test "uf50-0971.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0971.cnf")
}

///|
test "uf50-0448.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0448.cnf")
}

///|
test "uf50-0343.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0343.cnf")
}

///|
test "uf50-035.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-035.cnf")
}

///|
test "uf50-031.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-031.cnf")
}

///|
test "uf50-0581.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0581.cnf")
}

///|
test "uf50-0597.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0597.cnf")
}

///|
test "uf50-0946.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0946.cnf")
}

///|
test "uf50-034.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-034.cnf")
}

///|
test "uf50-0792.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0792.cnf")
}

///|
test "uf50-0583.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0583.cnf")
}

///|
test "uf50-0887.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0887.cnf")
}

///|
test "uf50-0506.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0506.cnf")
}

///|
test "uf50-059.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-059.cnf")
}

///|
test "uf50-0674.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0674.cnf")
}

///|
test "uf50-0133.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0133.cnf")
}

///|
test "uf50-0684.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0684.cnf")
}

///|
test "uf50-053.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-053.cnf")
}

///|
test "uf50-0981.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0981.cnf")
}

///|
test "uf50-0355.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0355.cnf")
}

///|
test "uf50-0704.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0704.cnf")
}

///|
test "uf50-0377.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0377.cnf")
}

///|
test "uf50-025.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-025.cnf")
}

///|
test "uf50-0362.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0362.cnf")
}

///|
test "uf50-0373.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0373.cnf")
}

///|
test "uf50-0340.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0340.cnf")
}

///|
test "uf50-0532.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0532.cnf")
}

///|
test "uf50-0319.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0319.cnf")
}

///|
test "uf50-0325.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0325.cnf")
}

///|
test "uf50-0889.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0889.cnf")
}

///|
test "uf50-0207.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0207.cnf")
}

///|
test "uf50-065.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-065.cnf")
}

///|
test "uf50-0312.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0312.cnf")
}

///|
test "uf50-0561.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0561.cnf")
}

///|
test "uf50-0293.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0293.cnf")
}

///|
test "uf50-0310.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0310.cnf")
}

///|
test "uf50-0867.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0867.cnf")
}

///|
test "uf50-061.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-061.cnf")
}

///|
test "uf50-083.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-083.cnf")
}

///|
test "uf50-0215.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0215.cnf")
}

///|
test "uf50-0156.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0156.cnf")
}

///|
test "uf50-0979.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0979.cnf")
}

///|
test "uf50-0691.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0691.cnf")
}

///|
test "uf50-0195.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0195.cnf")
}

///|
test "uf50-0254.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0254.cnf")
}

///|
test "uf50-0572.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0572.cnf")
}

///|
test "uf50-0874.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0874.cnf")
}

///|
test "uf50-082.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-082.cnf")
}

///|
test "uf50-0642.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0642.cnf")
}

///|
test "uf50-0395.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0395.cnf")
}

///|
test "uf50-0204.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0204.cnf")
}

///|
test "uf50-0574.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0574.cnf")
}

///|
test "uf50-015.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-015.cnf")
}

///|
test "uf50-0540.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0540.cnf")
}

///|
test "uf50-0188.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0188.cnf")
}

///|
test "uf50-0533.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0533.cnf")
}

///|
test "uf50-0165.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0165.cnf")
}

///|
test "uf50-0738.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0738.cnf")
}

///|
test "uf50-0252.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0252.cnf")
}

///|
test "uf50-038.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-038.cnf")
}

///|
test "uf50-0354.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0354.cnf")
}

///|
test "uf50-0836.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0836.cnf")
}

///|
test "uf50-0498.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0498.cnf")
}

///|
test "uf50-0588.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0588.cnf")
}

///|
test "uf50-0877.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0877.cnf")
}

///|
test "uf50-0610.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0610.cnf")
}

///|
test "uf50-0521.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0521.cnf")
}

///|
test "uf50-0873.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0873.cnf")
}

///|
test "uf50-0402.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0402.cnf")
}

///|
test "uf50-0316.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0316.cnf")
}

///|
test "uf50-0460.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0460.cnf")
}

///|
test "uf50-0534.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0534.cnf")
}

///|
test "uf50-0213.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0213.cnf")
}

///|
test "uf50-0126.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0126.cnf")
}

///|
test "uf50-0174.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0174.cnf")
}

///|
test "uf50-087.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-087.cnf")
}

///|
test "uf50-0145.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0145.cnf")
}

///|
test "uf50-0928.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0928.cnf")
}

///|
test "uf50-0863.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0863.cnf")
}

///|
test "uf50-013.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-013.cnf")
}

///|
test "uf50-0370.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0370.cnf")
}

///|
test "uf50-0138.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0138.cnf")
}

///|
test "uf50-0707.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0707.cnf")
}

///|
test "uf50-0895.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0895.cnf")
}

///|
test "uf50-0987.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0987.cnf")
}

///|
test "uf50-0883.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0883.cnf")
}

///|
test "uf50-0789.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0789.cnf")
}

///|
test "uf50-0267.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0267.cnf")
}

///|
test "uf50-0256.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0256.cnf")
}

///|
test "uf50-0997.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0997.cnf")
}

///|
test "uf50-0587.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0587.cnf")
}

///|
test "uf50-0124.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0124.cnf")
}

///|
test "uf50-0779.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0779.cnf")
}

///|
test "uf50-0336.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0336.cnf")
}

///|
test "uf50-0265.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0265.cnf")
}

///|
test "uf50-0185.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0185.cnf")
}

///|
test "uf50-0500.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0500.cnf")
}

///|
test "uf50-0628.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0628.cnf")
}

///|
test "uf50-0230.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0230.cnf")
}

///|
test "uf50-0885.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0885.cnf")
}

///|
test "uf50-0754.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0754.cnf")
}

///|
test "uf50-0551.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0551.cnf")
}

///|
test "uf50-0414.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0414.cnf")
}

///|
test "uf50-0147.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0147.cnf")
}

///|
test "uf50-0798.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0798.cnf")
}

///|
test "uf50-0624.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0624.cnf")
}

///|
test "uf50-0799.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0799.cnf")
}

///|
test "uf50-0241.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0241.cnf")
}

///|
test "uf50-0486.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0486.cnf")
}

///|
test "uf50-0960.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0960.cnf")
}

///|
test "uf50-091.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-091.cnf")
}

///|
test "uf50-0246.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0246.cnf")
}

///|
test "uf50-0504.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0504.cnf")
}

///|
test "uf50-0846.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0846.cnf")
}

///|
test "uf50-0344.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0344.cnf")
}

///|
test "uf50-0240.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0240.cnf")
}

///|
test "uf50-0900.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0900.cnf")
}

///|
test "uf50-0382.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0382.cnf")
}

///|
test "uf50-0710.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0710.cnf")
}

///|
test "uf50-0550.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0550.cnf")
}

///|
test "uf50-0840.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0840.cnf")
}

///|
test "uf50-0673.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0673.cnf")
}

///|
test "uf50-042.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-042.cnf")
}

///|
test "uf50-0163.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0163.cnf")
}

///|
test "uf50-0250.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0250.cnf")
}

///|
test "uf50-0888.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0888.cnf")
}

///|
test "uf50-0672.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0672.cnf")
}

///|
test "uf50-0257.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0257.cnf")
}

///|
test "uf50-0594.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0594.cnf")
}

///|
test "uf50-0329.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0329.cnf")
}

///|
test "uf50-0808.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0808.cnf")
}

///|
test "uf50-0958.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0958.cnf")
}

///|
test "uf50-0527.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0527.cnf")
}

///|
test "uf50-0882.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0882.cnf")
}

///|
test "uf50-0528.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0528.cnf")
}

///|
test "uf50-0158.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0158.cnf")
}

///|
test "uf50-0154.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0154.cnf")
}

///|
test "uf50-0905.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0905.cnf")
}

///|
test "uf50-0939.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0939.cnf")
}

///|
test "uf50-0415.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0415.cnf")
}

///|
test "uf50-0820.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0820.cnf")
}

///|
test "uf50-0648.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0648.cnf")
}

///|
test "uf50-0320.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0320.cnf")
}

///|
test "uf50-0681.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0681.cnf")
}

///|
test "uf50-0586.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0586.cnf")
}

///|
test "uf50-0454.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0454.cnf")
}

///|
test "uf50-0426.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0426.cnf")
}

///|
test "uf50-0505.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0505.cnf")
}

///|
test "uf50-0600.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0600.cnf")
}

///|
test "uf50-0458.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0458.cnf")
}

///|
test "uf50-0461.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0461.cnf")
}

///|
test "uf50-0656.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0656.cnf")
}

///|
test "uf50-0488.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0488.cnf")
}

///|
test "uf50-0856.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0856.cnf")
}

///|
test "uf50-0400.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0400.cnf")
}

///|
test "uf50-0164.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0164.cnf")
}

///|
test "uf50-0283.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0283.cnf")
}

///|
test "uf50-0115.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0115.cnf")
}

///|
test "uf50-0157.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0157.cnf")
}

///|
test "uf50-0371.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0371.cnf")
}

///|
test "uf50-0434.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0434.cnf")
}

///|
test "uf50-0823.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0823.cnf")
}

///|
test "uf50-0830.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0830.cnf")
}

///|
test "uf50-0143.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0143.cnf")
}

///|
test "uf50-0245.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0245.cnf")
}

///|
test "uf50-0657.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0657.cnf")
}

///|
test "uf50-0130.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0130.cnf")
}

///|
test "uf50-0769.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0769.cnf")
}

///|
test "uf50-021.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-021.cnf")
}

///|
test "uf50-096.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-096.cnf")
}

///|
test "uf50-0367.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0367.cnf")
}

///|
test "uf50-0194.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0194.cnf")
}

///|
test "uf50-0391.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0391.cnf")
}

///|
test "uf50-0217.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0217.cnf")
}

///|
test "uf50-0502.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0502.cnf")
}

///|
test "uf50-0598.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0598.cnf")
}

///|
test "uf50-0568.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0568.cnf")
}

///|
test "uf50-0443.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0443.cnf")
}

///|
test "uf50-0514.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0514.cnf")
}

///|
test "uf50-0569.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0569.cnf")
}

///|
test "uf50-0706.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0706.cnf")
}

///|
test "uf50-0168.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0168.cnf")
}

///|
test "uf50-0767.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0767.cnf")
}

///|
test "uf50-0650.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0650.cnf")
}

///|
test "uf50-0180.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0180.cnf")
}

///|
test "uf50-0372.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0372.cnf")
}

///|
test "uf50-0552.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0552.cnf")
}

///|
test "uf50-0187.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0187.cnf")
}

///|
test "uf50-0345.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0345.cnf")
}

///|
test "uf50-0477.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0477.cnf")
}

///|
test "uf50-0643.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0643.cnf")
}

///|
test "uf50-0632.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0632.cnf")
}

///|
test "uf50-0237.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0237.cnf")
}

///|
test "uf50-0430.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0430.cnf")
}

///|
test "uf50-093.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-093.cnf")
}

///|
test "uf50-0953.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0953.cnf")
}

///|
test "uf50-0864.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0864.cnf")
}

///|
test "uf50-0474.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0474.cnf")
}

///|
test "uf50-0909.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0909.cnf")
}

///|
test "uf50-0618.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0618.cnf")
}

///|
test "uf50-0906.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0906.cnf")
}

///|
test "uf50-090.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-090.cnf")
}

///|
test "uf50-0109.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0109.cnf")
}

///|
test "uf50-0564.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0564.cnf")
}

///|
test "uf50-0741.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0741.cnf")
}

///|
test "uf50-0520.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0520.cnf")
}

///|
test "uf50-0137.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0137.cnf")
}

///|
test "uf50-0570.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0570.cnf")
}

///|
test "uf50-0200.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0200.cnf")
}

///|
test "uf50-03.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-03.cnf")
}

///|
test "uf50-0844.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0844.cnf")
}

///|
test "uf50-0931.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0931.cnf")
}

///|
test "uf50-0543.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0543.cnf")
}

///|
test "uf50-0496.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0496.cnf")
}

///|
test "uf50-0235.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0235.cnf")
}

///|
test "uf50-0743.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0743.cnf")
}

///|
test "uf50-0636.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0636.cnf")
}

///|
test "uf50-0277.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0277.cnf")
}

///|
test "uf50-0231.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0231.cnf")
}

///|
test "uf50-0796.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0796.cnf")
}

///|
test "uf50-0394.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0394.cnf")
}

///|
test "uf50-0368.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0368.cnf")
}

///|
test "uf50-0155.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0155.cnf")
}

///|
test "uf50-0963.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0963.cnf")
}

///|
test "uf50-0655.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0655.cnf")
}

///|
test "uf50-0305.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0305.cnf")
}

///|
test "uf50-0866.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0866.cnf")
}

///|
test "uf50-0225.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0225.cnf")
}

///|
test "uf50-0936.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0936.cnf")
}

///|
test "uf50-0522.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0522.cnf")
}

///|
test "uf50-0593.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0593.cnf")
}

///|
test "uf50-0689.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0689.cnf")
}

///|
test "uf50-0282.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0282.cnf")
}

///|
test "uf50-0861.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0861.cnf")
}

///|
test "uf50-0843.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0843.cnf")
}

///|
test "uf50-0285.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0285.cnf")
}

///|
test "uf50-0635.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0635.cnf")
}

///|
test "uf50-0108.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0108.cnf")
}

///|
test "uf50-066.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-066.cnf")
}

///|
test "uf50-0698.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0698.cnf")
}

///|
test "uf50-0871.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0871.cnf")
}

///|
test "uf50-0747.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0747.cnf")
}

///|
test "uf50-0726.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0726.cnf")
}

///|
test "uf50-0731.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0731.cnf")
}

///|
test "uf50-055.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-055.cnf")
}

///|
test "uf50-0639.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0639.cnf")
}

///|
test "uf50-0248.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0248.cnf")
}

///|
test "uf50-030.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-030.cnf")
}

///|
test "uf50-0122.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0122.cnf")
}

///|
test "uf50-0485.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0485.cnf")
}

///|
test "uf50-0292.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0292.cnf")
}

///|
test "uf50-0191.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0191.cnf")
}

///|
test "uf50-0131.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0131.cnf")
}

///|
test "uf50-0694.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0694.cnf")
}

///|
test "uf50-0605.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0605.cnf")
}

///|
test "uf50-0178.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0178.cnf")
}

///|
test "uf50-0686.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0686.cnf")
}

///|
test "uf50-0688.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0688.cnf")
}

///|
test "uf50-0890.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0890.cnf")
}

///|
test "uf50-0641.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0641.cnf")
}

///|
test "uf50-0176.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0176.cnf")
}

///|
test "uf50-0713.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0713.cnf")
}

///|
test "uf50-0335.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0335.cnf")
}

///|
test "uf50-0453.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0453.cnf")
}

///|
test "uf50-0379.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0379.cnf")
}

///|
test "uf50-043.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-043.cnf")
}

///|
test "uf50-088.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-088.cnf")
}

///|
test "uf50-0727.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0727.cnf")
}

///|
test "uf50-0238.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0238.cnf")
}

///|
test "uf50-0433.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0433.cnf")
}

///|
test "uf50-0287.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0287.cnf")
}

///|
test "uf50-0579.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0579.cnf")
}

///|
test "uf50-0910.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0910.cnf")
}

///|
test "uf50-095.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-095.cnf")
}

///|
test "uf50-0968.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0968.cnf")
}

///|
test "uf50-0376.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0376.cnf")
}

///|
test "uf50-0278.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0278.cnf")
}

///|
test "uf50-0797.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0797.cnf")
}

///|
test "uf50-0538.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0538.cnf")
}

///|
test "uf50-0473.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0473.cnf")
}

///|
test "uf50-0412.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0412.cnf")
}

///|
test "uf50-054.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-054.cnf")
}

///|
test "uf50-0383.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0383.cnf")
}

///|
test "uf50-040.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-040.cnf")
}

///|
test "uf50-084.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-084.cnf")
}

///|
test "uf50-0853.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0853.cnf")
}

///|
test "uf50-0612.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0612.cnf")
}

///|
test "uf50-0647.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0647.cnf")
}

///|
test "uf50-0175.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0175.cnf")
}

///|
test "uf50-0416.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0416.cnf")
}

///|
test "uf50-0110.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0110.cnf")
}

///|
test "uf50-0720.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0720.cnf")
}

///|
test "uf50-0904.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0904.cnf")
}

///|
test "uf50-0541.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0541.cnf")
}

///|
test "uf50-0202.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0202.cnf")
}

///|
test "uf50-0592.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0592.cnf")
}

///|
test "uf50-0418.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0418.cnf")
}

///|
test "uf50-0307.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0307.cnf")
}

///|
test "uf50-097.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-097.cnf")
}

///|
test "uf50-0908.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0908.cnf")
}

///|
test "uf50-0148.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0148.cnf")
}

///|
test "uf50-0566.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0566.cnf")
}

///|
test "uf50-0627.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0627.cnf")
}

///|
test "uf50-0512.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0512.cnf")
}

///|
test "uf50-033.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-033.cnf")
}

///|
test "uf50-0513.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0513.cnf")
}

///|
test "uf50-0985.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0985.cnf")
}

///|
test "uf50-050.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-050.cnf")
}

///|
test "uf50-0102.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0102.cnf")
}

///|
test "uf50-0664.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0664.cnf")
}

///|
test "uf50-0661.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0661.cnf")
}

///|
test "uf50-0549.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0549.cnf")
}

///|
test "uf50-0160.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0160.cnf")
}

///|
test "uf50-0937.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0937.cnf")
}

///|
test "uf50-0602.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0602.cnf")
}

///|
test "uf50-032.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-032.cnf")
}

///|
test "uf50-018.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-018.cnf")
}

///|
test "uf50-0567.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0567.cnf")
}

///|
test "uf50-068.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-068.cnf")
}

///|
test "uf50-0951.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0951.cnf")
}

///|
test "uf50-0330.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0330.cnf")
}

///|
test "uf50-0159.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0159.cnf")
}

///|
test "uf50-089.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-089.cnf")
}

///|
test "uf50-0712.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0712.cnf")
}

///|
test "uf50-0249.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0249.cnf")
}

///|
test "uf50-0683.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0683.cnf")
}

///|
test "uf50-0759.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0759.cnf")
}

///|
test "uf50-0318.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0318.cnf")
}

///|
test "uf50-0805.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0805.cnf")
}

///|
test "uf50-0205.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0205.cnf")
}

///|
test "uf50-0127.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0127.cnf")
}

///|
test "uf50-029.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-029.cnf")
}

///|
test "uf50-0360.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0360.cnf")
}

///|
test "uf50-0742.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0742.cnf")
}

///|
test "uf50-0911.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0911.cnf")
}

///|
test "uf50-0358.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0358.cnf")
}

///|
test "uf50-0980.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0980.cnf")
}

///|
test "uf50-05.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-05.cnf")
}

///|
test "uf50-0782.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0782.cnf")
}

///|
test "uf50-0768.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0768.cnf")
}

///|
test "uf50-0918.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0918.cnf")
}

///|
test "uf50-0651.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0651.cnf")
}

///|
test "uf50-0929.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0929.cnf")
}

///|
test "uf50-0184.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0184.cnf")
}

///|
test "uf50-0599.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0599.cnf")
}

///|
test "uf50-0466.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0466.cnf")
}

///|
test "uf50-0503.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0503.cnf")
}

///|
test "uf50-0812.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0812.cnf")
}

///|
test "uf50-0841.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0841.cnf")
}

///|
test "uf50-0523.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0523.cnf")
}

///|
test "uf50-0196.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0196.cnf")
}

///|
test "uf50-0745.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0745.cnf")
}

///|
test "uf50-0294.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0294.cnf")
}

///|
test "uf50-0465.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0465.cnf")
}

///|
test "uf50-0388.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0388.cnf")
}

///|
test "uf50-0974.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0974.cnf")
}

///|
test "uf50-0795.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0795.cnf")
}

///|
test "uf50-0167.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0167.cnf")
}

///|
test "uf50-0494.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0494.cnf")
}

///|
test "uf50-0848.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0848.cnf")
}

///|
test "uf50-077.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-077.cnf")
}

///|
test "uf50-0865.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0865.cnf")
}

///|
test "uf50-0221.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0221.cnf")
}

///|
test "uf50-0917.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0917.cnf")
}

///|
test "uf50-0584.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0584.cnf")
}

///|
test "uf50-0492.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0492.cnf")
}

///|
test "uf50-0186.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0186.cnf")
}

///|
test "uf50-0539.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0539.cnf")
}

///|
test "uf50-0397.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0397.cnf")
}

///|
test "uf50-0324.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0324.cnf")
}

///|
test "uf50-0255.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0255.cnf")
}

///|
test "uf50-0703.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0703.cnf")
}

///|
test "uf50-0757.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0757.cnf")
}

///|
test "uf50-0403.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0403.cnf")
}

///|
test "uf50-0976.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0976.cnf")
}

///|
test "uf50-0884.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0884.cnf")
}

///|
test "uf50-0954.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0954.cnf")
}

///|
test "uf50-062.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-062.cnf")
}

///|
test "uf50-0471.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0471.cnf")
}

///|
test "uf50-0777.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0777.cnf")
}

///|
test "uf50-0760.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0760.cnf")
}

///|
test "uf50-0286.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0286.cnf")
}

///|
test "uf50-0559.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0559.cnf")
}

///|
test "uf50-0735.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0735.cnf")
}

///|
test "uf50-0524.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0524.cnf")
}

///|
test "uf50-0831.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0831.cnf")
}

///|
test "uf50-02.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-02.cnf")
}

///|
test "uf50-0226.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0226.cnf")
}

///|
test "uf50-070.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-070.cnf")
}

///|
test "uf50-0338.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0338.cnf")
}

///|
test "uf50-0784.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0784.cnf")
}

///|
test "uf50-0209.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0209.cnf")
}

///|
test "uf50-0411.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0411.cnf")
}

///|
test "uf50-0876.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0876.cnf")
}

///|
test "uf50-0719.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0719.cnf")
}

///|
test "uf50-0152.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0152.cnf")
}

///|
test "uf50-0407.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0407.cnf")
}

///|
test "uf50-0701.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0701.cnf")
}

///|
test "uf50-0912.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0912.cnf")
}

///|
test "uf50-0654.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0654.cnf")
}

///|
test "uf50-0595.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0595.cnf")
}

///|
test "uf50-0996.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0996.cnf")
}

///|
test "uf50-0606.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0606.cnf")
}

///|
test "uf50-0825.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0825.cnf")
}

///|
test "uf50-0964.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0964.cnf")
}

///|
test "uf50-0380.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0380.cnf")
}

///|
test "uf50-0965.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0965.cnf")
}

///|
test "uf50-0518.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0518.cnf")
}

///|
test "uf50-0670.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0670.cnf")
}

///|
test "uf50-0490.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0490.cnf")
}

///|
test "uf50-0982.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0982.cnf")
}

///|
test "uf50-01000.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-01000.cnf")
}

///|
test "uf50-0629.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0629.cnf")
}

///|
test "uf50-064.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-064.cnf")
}

///|
test "uf50-0385.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0385.cnf")
}

///|
test "uf50-080.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-080.cnf")
}

///|
test "uf50-0761.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0761.cnf")
}

///|
test "uf50-0410.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0410.cnf")
}

///|
test "uf50-0392.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0392.cnf")
}

///|
test "uf50-0346.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0346.cnf")
}

///|
test "uf50-024.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-024.cnf")
}

///|
test "uf50-016.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-016.cnf")
}

///|
test "uf50-0652.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0652.cnf")
}

///|
test "uf50-0423.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0423.cnf")
}

///|
test "uf50-0577.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0577.cnf")
}

///|
test "uf50-0947.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0947.cnf")
}

///|
test "uf50-0548.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0548.cnf")
}

///|
test "uf50-0959.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0959.cnf")
}

///|
test "uf50-0153.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0153.cnf")
}

///|
test "uf50-04.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-04.cnf")
}

///|
test "uf50-0705.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0705.cnf")
}

///|
test "uf50-0771.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0771.cnf")
}

///|
test "uf50-0990.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0990.cnf")
}

///|
test "uf50-0781.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0781.cnf")
}

///|
test "uf50-0478.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0478.cnf")
}

///|
test "uf50-0508.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0508.cnf")
}

///|
test "uf50-0173.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0173.cnf")
}

///|
test "uf50-0404.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0404.cnf")
}

///|
test "uf50-022.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-022.cnf")
}

///|
test "uf50-0301.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0301.cnf")
}

///|
test "uf50-0499.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0499.cnf")
}

///|
test "uf50-0690.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0690.cnf")
}

///|
test "uf50-0740.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0740.cnf")
}

///|
test "uf50-0676.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0676.cnf")
}

///|
test "uf50-0170.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0170.cnf")
}

///|
test "uf50-0140.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0140.cnf")
}

///|
test "uf50-074.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-074.cnf")
}

///|
test "uf50-0206.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0206.cnf")
}

///|
test "uf50-0553.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0553.cnf")
}

///|
test "uf50-0644.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0644.cnf")
}

///|
test "uf50-028.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-028.cnf")
}

///|
test "uf50-0390.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0390.cnf")
}

///|
test "uf50-0386.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0386.cnf")
}

///|
test "uf50-0218.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0218.cnf")
}

///|
test "uf50-0222.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0222.cnf")
}

///|
test "uf50-0451.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0451.cnf")
}

///|
test "uf50-0457.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0457.cnf")
}

///|
test "uf50-0822.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0822.cnf")
}

///|
test "uf50-0666.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0666.cnf")
}

///|
test "uf50-0493.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0493.cnf")
}

///|
test "uf50-0302.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0302.cnf")
}

///|
test "uf50-0262.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0262.cnf")
}

///|
test "uf50-0620.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0620.cnf")
}

///|
test "uf50-0992.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0992.cnf")
}

///|
test "uf50-010.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-010.cnf")
}

///|
test "uf50-0658.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0658.cnf")
}

///|
test "uf50-057.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-057.cnf")
}

///|
test "uf50-0201.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0201.cnf")
}

///|
test "uf50-0962.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0962.cnf")
}

///|
test "uf50-0913.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0913.cnf")
}

///|
test "uf50-0780.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0780.cnf")
}

///|
test "uf50-0817.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0817.cnf")
}

///|
test "uf50-0986.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0986.cnf")
}

///|
test "uf50-0870.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0870.cnf")
}

///|
test "uf50-052.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-052.cnf")
}

///|
test "uf50-0356.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0356.cnf")
}

///|
test "uf50-0393.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0393.cnf")
}

///|
test "uf50-0398.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0398.cnf")
}

///|
test "uf50-0349.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0349.cnf")
}

///|
test "uf50-0967.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0967.cnf")
}

///|
test "uf50-0827.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0827.cnf")
}

///|
test "uf50-0679.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0679.cnf")
}

///|
test "uf50-0284.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0284.cnf")
}

///|
test "uf50-020.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-020.cnf")
}

///|
test "uf50-0243.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0243.cnf")
}

///|
test "uf50-0921.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0921.cnf")
}

///|
test "uf50-098.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-098.cnf")
}

///|
test "uf50-0756.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0756.cnf")
}

///|
test "uf50-0337.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0337.cnf")
}

///|
test "uf50-0948.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0948.cnf")
}

///|
test "uf50-0850.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0850.cnf")
}

///|
test "uf50-0317.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0317.cnf")
}

///|
test "uf50-0556.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0556.cnf")
}

///|
test "uf50-0625.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0625.cnf")
}

///|
test "uf50-0203.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0203.cnf")
}

///|
test "uf50-0144.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0144.cnf")
}

///|
test "uf50-0721.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0721.cnf")
}

///|
test "uf50-0862.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0862.cnf")
}

///|
test "uf50-019.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-019.cnf")
}

///|
test "uf50-0589.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0589.cnf")
}

///|
test "uf50-0401.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0401.cnf")
}

///|
test "uf50-0482.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0482.cnf")
}

///|
test "uf50-0872.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0872.cnf")
}

///|
test "uf50-0219.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0219.cnf")
}

///|
test "uf50-0619.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0619.cnf")
}

///|
test "uf50-0744.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0744.cnf")
}

///|
test "uf50-037.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-037.cnf")
}

///|
test "uf50-0314.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0314.cnf")
}

///|
test "uf50-0591.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0591.cnf")
}

///|
test "uf50-0585.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0585.cnf")
}

///|
test "uf50-0530.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0530.cnf")
}

///|
test "uf50-0300.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0300.cnf")
}

///|
test "uf50-0881.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0881.cnf")
}

///|
test "uf50-0565.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0565.cnf")
}

///|
test "uf50-049.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-049.cnf")
}

///|
test "uf50-0702.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0702.cnf")
}

///|
test "uf50-0421.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0421.cnf")
}

///|
test "uf50-0944.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0944.cnf")
}

///|
test "uf50-0732.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0732.cnf")
}

///|
test "uf50-0765.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0765.cnf")
}

///|
test "uf50-0875.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0875.cnf")
}

///|
test "uf50-0446.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0446.cnf")
}

///|
test "uf50-0748.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0748.cnf")
}

///|
test "uf50-0487.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0487.cnf")
}

///|
test "uf50-0507.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0507.cnf")
}

///|
test "uf50-0228.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0228.cnf")
}

///|
test "uf50-0112.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0112.cnf")
}

///|
test "uf50-0786.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0786.cnf")
}

///|
test "uf50-0813.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0813.cnf")
}

///|
test "uf50-0264.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0264.cnf")
}

///|
test "uf50-0166.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0166.cnf")
}

///|
test "uf50-0438.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0438.cnf")
}

///|
test "uf50-0730.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0730.cnf")
}

///|
test "uf50-0715.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0715.cnf")
}

///|
test "uf50-0854.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0854.cnf")
}

///|
test "uf50-0638.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0638.cnf")
}

///|
test "uf50-0408.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0408.cnf")
}

///|
test "uf50-0733.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0733.cnf")
}

///|
test "uf50-092.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-092.cnf")
}

///|
test "uf50-0495.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0495.cnf")
}

///|
test "uf50-0949.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0949.cnf")
}

///|
test "uf50-0925.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0925.cnf")
}

///|
test "uf50-0770.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0770.cnf")
}

///|
test "uf50-0424.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0424.cnf")
}

///|
test "uf50-0753.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0753.cnf")
}

///|
test "uf50-0914.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0914.cnf")
}

///|
test "uf50-0139.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0139.cnf")
}

///|
test "uf50-0409.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0409.cnf")
}

///|
test "uf50-0123.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0123.cnf")
}

///|
test "uf50-0405.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0405.cnf")
}

///|
test "uf50-045.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-045.cnf")
}

///|
test "uf50-0924.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0924.cnf")
}

///|
test "uf50-0751.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0751.cnf")
}

///|
test "uf50-0193.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0193.cnf")
}

///|
test "uf50-0901.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0901.cnf")
}

///|
test "uf50-0934.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0934.cnf")
}

///|
test "uf50-0497.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0497.cnf")
}

///|
test "uf50-014.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-014.cnf")
}

///|
test "uf50-0903.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0903.cnf")
}

///|
test "uf50-0455.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0455.cnf")
}

///|
test "uf50-063.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-063.cnf")
}

///|
test "uf50-0677.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0677.cnf")
}

///|
test "uf50-0952.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0952.cnf")
}

///|
test "uf50-0469.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0469.cnf")
}

///|
test "uf50-0467.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0467.cnf")
}

///|
test "uf50-0932.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0932.cnf")
}

///|
test "uf50-0234.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0234.cnf")
}

///|
test "uf50-0100.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0100.cnf")
}

///|
test "uf50-0366.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0366.cnf")
}

///|
test "uf50-0957.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0957.cnf")
}

///|
test "uf50-0832.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0832.cnf")
}

///|
test "uf50-0809.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0809.cnf")
}

///|
test "uf50-0800.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0800.cnf")
}

///|
test "uf50-0775.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0775.cnf")
}

///|
test "uf50-0253.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0253.cnf")
}

///|
test "uf50-041.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-041.cnf")
}

///|
test "uf50-0855.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0855.cnf")
}

///|
test "uf50-0794.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0794.cnf")
}

///|
test "uf50-0802.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0802.cnf")
}

///|
test "uf50-0171.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0171.cnf")
}

///|
test "uf50-0480.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0480.cnf")
}

///|
test "uf50-0845.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0845.cnf")
}

///|
test "uf50-0943.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0943.cnf")
}

///|
test "uf50-0878.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0878.cnf")
}

///|
test "uf50-0189.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0189.cnf")
}

///|
test "uf50-0479.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0479.cnf")
}

///|
test "uf50-0172.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0172.cnf")
}

///|
test "uf50-0350.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0350.cnf")
}

///|
test "uf50-0755.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0755.cnf")
}

///|
test "uf50-0389.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0389.cnf")
}

///|
test "uf50-0452.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0452.cnf")
}

///|
test "uf50-0966.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0966.cnf")
}

///|
test "uf50-0596.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0596.cnf")
}

///|
test "uf50-0919.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0919.cnf")
}

///|
test "uf50-0696.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0696.cnf")
}

///|
test "uf50-0136.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0136.cnf")
}

///|
test "uf50-0746.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0746.cnf")
}

///|
test "uf50-0847.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0847.cnf")
}

///|
test "uf50-039.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-039.cnf")
}

///|
test "uf50-0941.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0941.cnf")
}

///|
test "uf50-0444.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0444.cnf")
}

///|
test "uf50-099.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-099.cnf")
}

///|
test "uf50-0630.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0630.cnf")
}

///|
test "uf50-0898.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0898.cnf")
}

///|
test "uf50-017.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-017.cnf")
}

///|
test "uf50-0978.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0978.cnf")
}

///|
test "uf50-0608.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0608.cnf")
}

///|
test "uf50-0529.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0529.cnf")
}

///|
test "uf50-0662.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0662.cnf")
}

///|
test "uf50-0149.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0149.cnf")
}

///|
test "uf50-0288.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0288.cnf")
}

///|
test "uf50-0263.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0263.cnf")
}

///|
test "uf50-0815.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0815.cnf")
}

///|
test "uf50-0291.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0291.cnf")
}

///|
test "uf50-067.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-067.cnf")
}

///|
test "uf50-0146.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0146.cnf")
}

///|
test "uf50-0590.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0590.cnf")
}

///|
test "uf50-0562.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0562.cnf")
}

///|
test "uf50-0547.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0547.cnf")
}

///|
test "uf50-0558.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0558.cnf")
}

///|
test "uf50-094.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-094.cnf")
}

///|
test "uf50-0984.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0984.cnf")
}

///|
test "uf50-0247.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0247.cnf")
}

///|
test "uf50-0450.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0450.cnf")
}

///|
test "uf50-0940.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0940.cnf")
}

///|
test "uf50-0582.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0582.cnf")
}

///|
test "uf50-0289.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0289.cnf")
}

///|
test "uf50-0975.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0975.cnf")
}

///|
test "uf50-0818.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0818.cnf")
}

///|
test "uf50-0682.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0682.cnf")
}

///|
test "uf50-0259.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0259.cnf")
}

///|
test "uf50-027.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-027.cnf")
}

///|
test "uf50-0571.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0571.cnf")
}

///|
test "uf50-0308.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0308.cnf")
}

///|
test "uf50-0660.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0660.cnf")
}

///|
test "uf50-0613.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0613.cnf")
}

///|
test "uf50-0211.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0211.cnf")
}

///|
test "uf50-0111.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0111.cnf")
}

///|
test "uf50-0475.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0475.cnf")
}

///|
test "uf50-081.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-081.cnf")
}

///|
test "uf50-0819.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0819.cnf")
}

///|
test "uf50-0107.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0107.cnf")
}

///|
test "uf50-0999.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0999.cnf")
}

///|
test "uf50-0363.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0363.cnf")
}

///|
test "uf50-0463.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0463.cnf")
}

///|
test "uf50-0121.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0121.cnf")
}

///|
test "uf50-0716.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0716.cnf")
}

///|
test "uf50-0653.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0653.cnf")
}

///|
test "uf50-0563.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0563.cnf")
}

///|
test "uf50-0950.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0950.cnf")
}

///|
test "uf50-0470.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0470.cnf")
}

///|
test "uf50-0116.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0116.cnf")
}

///|
test "uf50-0668.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0668.cnf")
}

///|
test "uf50-0736.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0736.cnf")
}

///|
test "uf50-0315.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0315.cnf")
}

///|
test "uf50-0938.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0938.cnf")
}

///|
test "uf50-0806.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0806.cnf")
}

///|
test "uf50-0351.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0351.cnf")
}

///|
test "uf50-0511.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0511.cnf")
}

///|
test "uf50-0849.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0849.cnf")
}

///|
test "uf50-0456.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0456.cnf")
}

///|
test "uf50-0880.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0880.cnf")
}

///|
test "uf50-0879.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0879.cnf")
}

///|
test "uf50-0141.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0141.cnf")
}

///|
test "uf50-0169.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0169.cnf")
}

///|
test "uf50-0271.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0271.cnf")
}

///|
test "uf50-0839.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0839.cnf")
}

///|
test "uf50-0417.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0417.cnf")
}

///|
test "uf50-0969.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0969.cnf")
}

///|
test "uf50-0239.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0239.cnf")
}

///|
test "uf50-0772.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0772.cnf")
}

///|
test "uf50-07.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-07.cnf")
}

///|
test "uf50-0441.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0441.cnf")
}

///|
test "uf50-0811.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0811.cnf")
}

///|
test "uf50-0693.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0693.cnf")
}

///|
test "uf50-0995.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0995.cnf")
}

///|
test "uf50-0326.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0326.cnf")
}

///|
test "uf50-0387.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0387.cnf")
}

///|
test "uf50-0810.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0810.cnf")
}

///|
test "uf50-0615.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0615.cnf")
}

///|
test "uf50-0117.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0117.cnf")
}

///|
test "uf50-0347.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0347.cnf")
}

///|
test "uf50-0296.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0296.cnf")
}

///|
test "uf50-0437.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0437.cnf")
}

///|
test "uf50-0129.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0129.cnf")
}

///|
test "uf50-0892.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0892.cnf")
}

///|
test "uf50-0214.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0214.cnf")
}

///|
test "uf50-0837.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0837.cnf")
}

///|
test "uf50-0821.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0821.cnf")
}

///|
test "uf50-0725.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0725.cnf")
}

///|
test "uf50-0977.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0977.cnf")
}

///|
test "uf50-0709.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0709.cnf")
}

///|
test "uf50-0361.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0361.cnf")
}

///|
test "uf50-071.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-071.cnf")
}

///|
test "uf50-0708.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0708.cnf")
}

///|
test "uf50-0942.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0942.cnf")
}

///|
test "uf50-0103.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0103.cnf")
}

///|
test "uf50-048.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-048.cnf")
}

///|
test "uf50-0714.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0714.cnf")
}

///|
test "uf50-0764.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0764.cnf")
}

///|
test "uf50-0101.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0101.cnf")
}

///|
test "uf50-0828.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0828.cnf")
}

///|
test "uf50-0816.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0816.cnf")
}

///|
test "uf50-0575.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0575.cnf")
}

///|
test "uf50-0334.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0334.cnf")
}

///|
test "uf50-0183.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0183.cnf")
}

///|
test "uf50-0669.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0669.cnf")
}

///|
test "uf50-0695.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0695.cnf")
}

///|
test "uf50-0835.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0835.cnf")
}

///|
test "uf50-0752.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0752.cnf")
}

///|
test "uf50-0922.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0922.cnf")
}

///|
test "uf50-0930.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0930.cnf")
}

///|
test "uf50-0838.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0838.cnf")
}

///|
test "uf50-0927.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0927.cnf")
}

///|
test "uf50-0935.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0935.cnf")
}

///|
test "uf50-0537.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0537.cnf")
}

///|
test "uf50-0197.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0197.cnf")
}

///|
test "uf50-0998.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0998.cnf")
}

///|
test "uf50-0749.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0749.cnf")
}

///|
test "uf50-0667.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0667.cnf")
}

///|
test "uf50-0260.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0260.cnf")
}

///|
test "uf50-0697.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0697.cnf")
}

///|
test "uf50-0609.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0609.cnf")
}

///|
test "uf50-0763.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0763.cnf")
}

///|
test "uf50-0179.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0179.cnf")
}

///|
test "uf50-0428.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0428.cnf")
}

///|
test "uf50-0739.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0739.cnf")
}

///|
test "uf50-0378.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0378.cnf")
}

///|
test "uf50-0515.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0515.cnf")
}

///|
test "uf50-0868.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0868.cnf")
}

///|
test "uf50-0427.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0427.cnf")
}

///|
test "uf50-0442.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0442.cnf")
}

///|
test "uf50-0436.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0436.cnf")
}

///|
test "uf50-0560.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0560.cnf")
}

///|
test "uf50-0614.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0614.cnf")
}

///|
test "uf50-0869.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0869.cnf")
}

///|
test "uf50-0276.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0276.cnf")
}

///|
test "uf50-0220.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0220.cnf")
}

///|
test "uf50-0181.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0181.cnf")
}

///|
test "uf50-0309.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0309.cnf")
}

///|
test "uf50-0834.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0834.cnf")
}

///|
test "uf50-0972.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0972.cnf")
}

///|
test "uf50-0852.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0852.cnf")
}

///|
test "uf50-0106.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0106.cnf")
}

///|
test "uf50-0793.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0793.cnf")
}

///|
test "uf50-0554.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0554.cnf")
}

///|
test "uf50-0272.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0272.cnf")
}

///|
test "uf50-0621.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0621.cnf")
}

///|
test "uf50-0295.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0295.cnf")
}

///|
test "uf50-0626.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0626.cnf")
}

///|
test "uf50-0678.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0678.cnf")
}

///|
test "uf50-046.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-046.cnf")
}

///|
test "uf50-0151.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0151.cnf")
}

///|
test "uf50-0119.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0119.cnf")
}

///|
test "uf50-0280.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0280.cnf")
}

///|
test "uf50-0776.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0776.cnf")
}

///|
test "uf50-0833.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0833.cnf")
}

///|
test "uf50-0341.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0341.cnf")
}

///|
test "uf50-0824.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0824.cnf")
}

///|
test "uf50-011.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-011.cnf")
}

///|
test "uf50-0509.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0509.cnf")
}

///|
test "uf50-0327.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0327.cnf")
}

///|
test "uf50-0323.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0323.cnf")
}

///|
test "uf50-0342.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0342.cnf")
}

///|
test "uf50-036.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-036.cnf")
}

///|
test "uf50-0860.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0860.cnf")
}

///|
test "uf50-0162.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0162.cnf")
}

///|
test "uf50-0758.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0758.cnf")
}

///|
test "uf50-0729.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0729.cnf")
}

///|
test "uf50-0281.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0281.cnf")
}

///|
test "uf50-0422.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0422.cnf")
}

///|
test "uf50-0894.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0894.cnf")
}

///|
test "uf50-0177.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0177.cnf")
}

///|
test "uf50-0788.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0788.cnf")
}

///|
test "uf50-0216.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0216.cnf")
}

///|
test "uf50-0396.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0396.cnf")
}

///|
test "uf50-0766.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0766.cnf")
}

///|
test "uf50-0261.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0261.cnf")
}

///|
test "uf50-058.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-058.cnf")
}

///|
test "uf50-0381.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0381.cnf")
}

///|
test "uf50-0290.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0290.cnf")
}

///|
test "uf50-0429.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0429.cnf")
}

///|
test "uf50-0555.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0555.cnf")
}

///|
test "uf50-06.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-06.cnf")
}

///|
test "uf50-0339.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0339.cnf")
}

///|
test "uf50-0135.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0135.cnf")
}

///|
test "uf50-0804.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0804.cnf")
}

///|
test "uf50-0270.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0270.cnf")
}

///|
test "uf50-0484.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0484.cnf")
}

///|
test "uf50-0724.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0724.cnf")
}

///|
test "uf50-0275.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0275.cnf")
}

///|
test "uf50-078.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-078.cnf")
}

///|
test "uf50-047.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-047.cnf")
}

///|
test "uf50-0190.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0190.cnf")
}

///|
test "uf50-0858.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0858.cnf")
}

///|
test "uf50-0374.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0374.cnf")
}

///|
test "uf50-0322.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0322.cnf")
}

///|
test "uf50-0481.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0481.cnf")
}

///|
test "uf50-056.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-056.cnf")
}

///|
test "uf50-0604.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0604.cnf")
}

///|
test "uf50-0132.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0132.cnf")
}

///|
test "uf50-0607.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0607.cnf")
}

///|
test "uf50-0331.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0331.cnf")
}

///|
test "uf50-0192.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0192.cnf")
}

///|
test "uf50-0364.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0364.cnf")
}

///|
test "uf50-0659.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0659.cnf")
}

///|
test "uf50-0227.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0227.cnf")
}

///|
test "uf50-0120.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0120.cnf")
}

///|
test "uf50-023.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-023.cnf")
}

///|
test "uf50-0634.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0634.cnf")
}

///|
test "uf50-0439.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0439.cnf")
}

///|
test "uf50-0535.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0535.cnf")
}

///|
test "uf50-0447.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0447.cnf")
}

///|
test "uf50-0640.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0640.cnf")
}

///|
test "uf50-0526.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0526.cnf")
}

///|
test "uf50-0542.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0542.cnf")
}

///|
test "uf50-012.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-012.cnf")
}

///|
test "uf50-0299.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0299.cnf")
}

///|
test "uf50-0557.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0557.cnf")
}

///|
test "uf50-085.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-085.cnf")
}

///|
test "uf50-0258.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0258.cnf")
}

///|
test "uf50-0722.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0722.cnf")
}

///|
test "uf50-0970.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0970.cnf")
}

///|
test "uf50-0223.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0223.cnf")
}

///|
test "uf50-0128.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0128.cnf")
}

///|
test "uf50-0425.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0425.cnf")
}

///|
test "uf50-0161.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0161.cnf")
}

///|
test "uf50-0210.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0210.cnf")
}

///|
test "uf50-0303.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0303.cnf")
}

///|
test "uf50-0783.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0783.cnf")
}

///|
test "uf50-0544.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0544.cnf")
}

///|
test "uf50-0692.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0692.cnf")
}

///|
test "uf50-08.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-08.cnf")
}

///|
test "uf50-0113.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0113.cnf")
}

///|
test "uf50-075.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-075.cnf")
}

///|
test "uf50-060.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-060.cnf")
}

///|
test "uf50-0365.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0365.cnf")
}

///|
test "uf50-0717.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0717.cnf")
}

///|
test "uf50-0232.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0232.cnf")
}

///|
test "uf50-0601.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0601.cnf")
}

///|
test "uf50-0649.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0649.cnf")
}

///|
test "uf50-0955.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0955.cnf")
}

///|
test "uf50-0893.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0893.cnf")
}

///|
test "uf50-0645.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0645.cnf")
}

///|
test "uf50-0631.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0631.cnf")
}

///|
test "uf50-0675.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0675.cnf")
}

///|
test "uf50-0891.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0891.cnf")
}

///|
test "uf50-0432.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0432.cnf")
}

///|
test "uf50-0134.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0134.cnf")
}

///|
test "uf50-0728.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0728.cnf")
}

///|
test "uf50-0956.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0956.cnf")
}

///|
test "uf50-0244.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0244.cnf")
}

///|
test "uf50-0491.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0491.cnf")
}

///|
test "uf50-0989.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0989.cnf")
}

///|
test "uf50-0266.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0266.cnf")
}

///|
test "uf50-0269.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0269.cnf")
}

///|
test "uf50-0328.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0328.cnf")
}

///|
test "uf50-0791.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0791.cnf")
}

///|
test "uf50-0104.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0104.cnf")
}

///|
test "uf50-0737.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0737.cnf")
}

///|
test "uf50-0413.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0413.cnf")
}

///|
test "uf50-0525.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0525.cnf")
}

///|
test "uf50-0546.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0546.cnf")
}

///|
test "uf50-0419.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0419.cnf")
}

///|
test "uf50-0896.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0896.cnf")
}

///|
test "uf50-0274.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0274.cnf")
}

///|
test "uf50-0790.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0790.cnf")
}

///|
test "uf50-0801.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0801.cnf")
}

///|
test "uf50-0994.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0994.cnf")
}

///|
test "uf50-0762.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0762.cnf")
}

///|
test "uf50-0510.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0510.cnf")
}

///|
test "uf50-073.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-073.cnf")
}

///|
test "uf50-0531.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0531.cnf")
}

///|
test "uf50-0926.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0926.cnf")
}

///|
test "uf50-0105.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0105.cnf")
}

///|
test "uf50-069.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-069.cnf")
}

///|
test "uf50-0332.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0332.cnf")
}

///|
test "uf50-0859.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0859.cnf")
}

///|
test "uf50-0298.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0298.cnf")
}

///|
test "uf50-0297.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0297.cnf")
}

///|
test "uf50-0431.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0431.cnf")
}

///|
test "uf50-0489.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0489.cnf")
}

///|
test "uf50-0616.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0616.cnf")
}

///|
test "uf50-0242.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0242.cnf")
}

///|
test "uf50-0578.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0578.cnf")
}

///|
test "uf50-0150.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0150.cnf")
}

///|
test "uf50-0711.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0711.cnf")
}

///|
test "uf50-0406.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0406.cnf")
}

///|
test "uf50-0279.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0279.cnf")
}

///|
test "uf50-0519.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0519.cnf")
}

///|
test "uf50-0633.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0633.cnf")
}

///|
test "uf50-0251.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0251.cnf")
}

///|
test "uf50-0787.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0787.cnf")
}

///|
test "uf50-0983.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0983.cnf")
}

///|
test "uf50-0476.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0476.cnf")
}

///|
test "uf50-0933.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0933.cnf")
}

///|
test "uf50-0304.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0304.cnf")
}

///|
test "uf50-0750.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0750.cnf")
}

///|
test "uf50-0333.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0333.cnf")
}

///|
test "uf50-076.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-076.cnf")
}

///|
test "uf50-0899.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0899.cnf")
}

///|
test "uf50-0961.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0961.cnf")
}

///|
test "uf50-0198.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0198.cnf")
}

///|
test "uf50-09.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-09.cnf")
}

///|
test "uf50-0687.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0687.cnf")
}

///|
test "uf50-072.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-072.cnf")
}

///|
test "uf50-0224.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0224.cnf")
}

///|
test "uf50-0118.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0118.cnf")
}

///|
test "uf50-0114.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0114.cnf")
}

///|
test "uf50-0718.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0718.cnf")
}

///|
test "uf50-0945.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0945.cnf")
}

///|
test "uf50-051.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-051.cnf")
}

///|
test "uf50-0536.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0536.cnf")
}

///|
test "uf50-0576.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0576.cnf")
}

///|
test "uf50-0229.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0229.cnf")
}

///|
test "uf50-0665.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0665.cnf")
}

///|
test "uf50-0440.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0440.cnf")
}

///|
test "uf50-0920.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0920.cnf")
}

///|
test "uf50-0420.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0420.cnf")
}

///|
test "uf50-0352.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0352.cnf")
}

///|
test "uf50-0646.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0646.cnf")
}

///|
test "uf50-0468.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0468.cnf")
}

///|
test "uf50-0472.cnf" {
  check_sat("./dimacs/uf50v218c/uf50-0472.cnf")
}
